using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CsEval.Generators.Model;

namespace CsEval.Generators.Emitters;

internal static class TypeMetadataEmitter
{
    public static string Emit(TypeRegistrationModel reg)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"file sealed class {reg.MetadataClassName} : global::CsEval.Aot.IAotTypeMetadata");
        sb.AppendLine("{");

        EmitTypeProperty(sb, reg);
        EmitTryGetProperty(sb, reg);
        EmitTrySetProperty(sb, reg);
        EmitTryGetField(sb, reg);
        EmitTrySetField(sb, reg);
        EmitTryGetIndex(sb, reg);
        EmitTrySetIndex(sb, reg);
        EmitTryGetStaticProperty(sb, reg);
        EmitTryGetStaticField(sb, reg);
        EmitTryCreateInstance(sb, reg);
        EmitTryInvokeMethod(sb, reg);
        EmitTryInvokeStaticMethod(sb, reg);

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string? EmitGenericInstantiations(ImmutableArray<TypeRegistrationModel> registrations)
    {
        var closedGenerics = registrations.Where(r => r.IsClosedGeneric).ToArray();
        if (closedGenerics.Length == 0)
            return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("file static class GenericInstantiations");
        sb.AppendLine("{");

        var seenFields = new HashSet<string>();
        foreach (var reg in closedGenerics)
        {
            var fieldName = "_" + SanitizeFieldName(reg.TypeFullName);
            if (!seenFields.Add(fieldName))
                continue;
            sb.AppendLine($"    static readonly global::System.Type {fieldName} = typeof({reg.TypeFullName});");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitTypeProperty(StringBuilder sb, TypeRegistrationModel reg)
    {
        sb.AppendLine($"    public global::System.Type Type => typeof({reg.TypeFullName});");
        sb.AppendLine();
    }

    private static void EmitTryGetProperty(StringBuilder sb, TypeRegistrationModel reg)
    {
        var instanceProps = reg.Properties.Where(p => p is { IsStatic: false, CanRead: true }).ToArray();

        sb.AppendLine("    public bool TryGetProperty(string name, object instance, out object? value)");
        sb.AppendLine("    {");

        if (instanceProps.Length > 0)
        {
            sb.AppendLine($"        var typed = ({reg.TypeFullName})instance;");
            sb.AppendLine("        switch (name)");
            sb.AppendLine("        {");
            foreach (var prop in instanceProps)
                sb.AppendLine($"            case \"{prop.Name}\": value = typed.{prop.Name}; return true;");
            sb.AppendLine("            default: value = default; return false;");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine("        value = default;");
            sb.AppendLine("        return false;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitTrySetProperty(StringBuilder sb, TypeRegistrationModel reg)
    {
        var writableProps = reg.Properties.Where(p => p is { IsStatic: false, CanWrite: true }).ToArray();

        sb.AppendLine("    public bool TrySetProperty(string name, object instance, object? value)");
        sb.AppendLine("    {");

        if (writableProps.Length > 0)
        {
            sb.AppendLine($"        var typed = ({reg.TypeFullName})instance;");
            sb.AppendLine("        switch (name)");
            sb.AppendLine("        {");
            foreach (var prop in writableProps)
                sb.AppendLine($"            case \"{prop.Name}\": typed.{prop.Name} = ({prop.TypeFullName})value!; return true;");
            sb.AppendLine("            default: return false;");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine("        return false;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitTryGetField(StringBuilder sb, TypeRegistrationModel reg)
    {
        var instanceFields = reg.Fields.Where(f => !f.IsStatic).ToArray();

        sb.AppendLine("    public bool TryGetField(string name, object instance, out object? value)");
        sb.AppendLine("    {");

        if (instanceFields.Length > 0)
        {
            sb.AppendLine($"        var typed = ({reg.TypeFullName})instance;");
            sb.AppendLine("        switch (name)");
            sb.AppendLine("        {");
            foreach (var field in instanceFields)
                sb.AppendLine($"            case \"{field.Name}\": value = typed.{field.Name}; return true;");
            sb.AppendLine("            default: value = default; return false;");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine("        value = default;");
            sb.AppendLine("        return false;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitTrySetField(StringBuilder sb, TypeRegistrationModel reg)
    {
        var writableFields = reg.Fields.Where(f => f is { IsStatic: false, IsReadOnly: false }).ToArray();

        sb.AppendLine("    public bool TrySetField(string name, object instance, object? value)");
        sb.AppendLine("    {");

        if (writableFields.Length > 0)
        {
            sb.AppendLine($"        var typed = ({reg.TypeFullName})instance;");
            sb.AppendLine("        switch (name)");
            sb.AppendLine("        {");
            foreach (var field in writableFields)
                sb.AppendLine($"            case \"{field.Name}\": typed.{field.Name} = ({field.TypeFullName})value!; return true;");
            sb.AppendLine("            default: return false;");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine("        return false;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitTryGetIndex(StringBuilder sb, TypeRegistrationModel reg)
    {
        var readableIndexers = reg.Indexers.Where(i => i.CanRead).ToArray();

        sb.AppendLine("    public bool TryGetIndex(object instance, object key, out object? value)");
        sb.AppendLine("    {");

        if (readableIndexers.Length > 0)
        {
            var idx = readableIndexers[0];
            sb.AppendLine($"        value = (({reg.TypeFullName})instance)[({idx.KeyTypeFullName})key];");
            sb.AppendLine("        return true;");
        }
        else
        {
            sb.AppendLine("        value = default;");
            sb.AppendLine("        return false;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitTrySetIndex(StringBuilder sb, TypeRegistrationModel reg)
    {
        var writableIndexers = reg.Indexers.Where(i => i.CanWrite).ToArray();

        sb.AppendLine("    public bool TrySetIndex(object instance, object key, object? value)");
        sb.AppendLine("    {");

        if (writableIndexers.Length > 0)
        {
            var idx = writableIndexers[0];
            sb.AppendLine($"        (({reg.TypeFullName})instance)[({idx.KeyTypeFullName})key] = ({idx.ValueTypeFullName})value!;");
            sb.AppendLine("        return true;");
        }
        else
        {
            sb.AppendLine("        return false;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitTryGetStaticProperty(StringBuilder sb, TypeRegistrationModel reg)
    {
        var staticProps = reg.Properties.Where(p => p is { IsStatic: true, CanRead: true }).ToArray();

        sb.AppendLine("    public bool TryGetStaticProperty(string name, out object? value)");
        sb.AppendLine("    {");

        if (staticProps.Length > 0)
        {
            sb.AppendLine("        switch (name)");
            sb.AppendLine("        {");
            foreach (var prop in staticProps)
                sb.AppendLine($"            case \"{prop.Name}\": value = {reg.TypeFullName}.{prop.Name}; return true;");
            sb.AppendLine("            default: value = default; return false;");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine("        value = default;");
            sb.AppendLine("        return false;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitTryGetStaticField(StringBuilder sb, TypeRegistrationModel reg)
    {
        var staticFields = reg.Fields.Where(f => f.IsStatic).ToArray();

        sb.AppendLine("    public bool TryGetStaticField(string name, out object? value)");
        sb.AppendLine("    {");

        if (staticFields.Length > 0)
        {
            sb.AppendLine("        switch (name)");
            sb.AppendLine("        {");
            foreach (var field in staticFields)
                sb.AppendLine($"            case \"{field.Name}\": value = {reg.TypeFullName}.{field.Name}; return true;");
            sb.AppendLine("            default: value = default; return false;");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine("        value = default;");
            sb.AppendLine("        return false;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitTryCreateInstance(StringBuilder sb, TypeRegistrationModel reg)
    {
        sb.AppendLine("    public bool TryCreateInstance(object?[] args, out object? instance)");
        sb.AppendLine("    {");

        if (reg.Constructors.Length > 0)
        {
            sb.AppendLine("        switch (args.Length)");
            sb.AppendLine("        {");

            // Group constructors by parameter count to handle overloads
            var byParamCount = reg.Constructors
                .GroupBy(c => c.Parameters.Length)
                .OrderBy(g => g.Key);

            foreach (var group in byParamCount)
            {
                var ctor = group.First(); // Take first overload for each param count
                if (ctor.Parameters.Length == 0)
                {
                    sb.AppendLine($"            case 0: instance = new {reg.TypeFullName}(); return true;");
                }
                else
                {
                    var args = string.Join(", ", ctor.Parameters.Select((p, i) => $"({p.TypeFullName})args[{i}]!"));
                    sb.AppendLine($"            case {ctor.Parameters.Length}: instance = new {reg.TypeFullName}({args}); return true;");
                }
            }

            sb.AppendLine("            default: instance = default; return false;");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine("        instance = default;");
            sb.AppendLine("        return false;");
        }

        sb.AppendLine("    }");
    }

    private static void EmitTryInvokeMethod(StringBuilder sb, TypeRegistrationModel reg)
    {
        var instanceMethods = reg.Methods.Where(m => !m.IsStatic).ToArray();

        sb.AppendLine();
        sb.AppendLine("    public bool TryInvokeMethod(string name, object instance, object?[] args, out object? result)");
        sb.AppendLine("    {");

        if (instanceMethods.Length > 0)
        {
            sb.AppendLine($"        var typed = ({reg.TypeFullName})instance;");
            sb.AppendLine("        switch (name)");
            sb.AppendLine("        {");

            foreach (var group in instanceMethods.GroupBy(m => m.Name))
            {
                sb.AppendLine($"            case \"{group.Key}\":");
                sb.AppendLine("                switch (args.Length)");
                sb.AppendLine("                {");

                var seenCounts = new HashSet<int>();
                foreach (var method in group)
                {
                    if (!seenCounts.Add(method.Parameters.Length))
                        continue;
                    var castArgs = string.Join(", ", method.Parameters.Select((p, i) => $"({p.TypeFullName})args[{i}]!"));
                    if (method.ReturnsVoid)
                    {
                        sb.AppendLine($"                    case {method.Parameters.Length}: typed.{method.Name}({castArgs}); result = null; return true;");
                    }
                    else
                    {
                        sb.AppendLine($"                    case {method.Parameters.Length}: result = typed.{method.Name}({castArgs}); return true;");
                    }
                }

                sb.AppendLine("                    default: break;");
                sb.AppendLine("                }");
                sb.AppendLine("                break;");
            }

            sb.AppendLine("        }");
            sb.AppendLine("        result = default;");
            sb.AppendLine("        return false;");
        }
        else
        {
            sb.AppendLine("        result = default;");
            sb.AppendLine("        return false;");
        }

        sb.AppendLine("    }");
    }

    private static void EmitTryInvokeStaticMethod(StringBuilder sb, TypeRegistrationModel reg)
    {
        var staticMethods = reg.Methods.Where(m => m.IsStatic).ToArray();

        sb.AppendLine();
        sb.AppendLine("    public bool TryInvokeStaticMethod(string name, object?[] args, out object? result)");
        sb.AppendLine("    {");

        if (staticMethods.Length > 0)
        {
            sb.AppendLine("        switch (name)");
            sb.AppendLine("        {");

            foreach (var group in staticMethods.GroupBy(m => m.Name))
            {
                sb.AppendLine($"            case \"{group.Key}\":");
                sb.AppendLine("                switch (args.Length)");
                sb.AppendLine("                {");

                var seenCounts = new HashSet<int>();
                foreach (var method in group)
                {
                    if (!seenCounts.Add(method.Parameters.Length))
                        continue;
                    var castArgs = string.Join(", ", method.Parameters.Select((p, i) => $"({p.TypeFullName})args[{i}]!"));
                    if (method.ReturnsVoid)
                    {
                        sb.AppendLine($"                    case {method.Parameters.Length}: {reg.TypeFullName}.{method.Name}({castArgs}); result = null; return true;");
                    }
                    else
                    {
                        sb.AppendLine($"                    case {method.Parameters.Length}: result = {reg.TypeFullName}.{method.Name}({castArgs}); return true;");
                    }
                }

                sb.AppendLine("                    default: break;");
                sb.AppendLine("                }");
                sb.AppendLine("                break;");
            }

            sb.AppendLine("        }");
            sb.AppendLine("        result = default;");
            sb.AppendLine("        return false;");
        }
        else
        {
            sb.AppendLine("        result = default;");
            sb.AppendLine("        return false;");
        }

        sb.AppendLine("    }");
    }

    private static string SanitizeFieldName(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }
        var result = sb.ToString();
        if (result.StartsWith("global__"))
            result = result.Substring("global__".Length);
        return result;
    }
}
