namespace CsEval;

[CsEvalRegistered(typeof(int))]
[CsEvalRegistered(typeof(long))]
[CsEvalRegistered(typeof(double))]
[CsEvalRegistered(typeof(float))]
[CsEvalRegistered(typeof(decimal))]
[CsEvalRegistered(typeof(bool))]
[CsEvalRegistered(typeof(char))]
[CsEvalRegistered(typeof(byte))]
[CsEvalRegistered(typeof(string))]
[CsEvalRegistered(typeof(object))]
[CsEvalRegistered(typeof(DateTime))]
[CsEvalRegistered(typeof(TimeSpan))]
[CsEvalRegistered(typeof(Guid))]
[CsEvalRegistered(typeof(Math))]
[CsEvalRegistered(typeof(Convert))]
[CsEvalRegistered(typeof(Environment))]
[CsEvalRegistered(typeof(Exception))]
[CsEvalRegistered(typeof(ArgumentException))]
[CsEvalRegistered(typeof(ArgumentNullException))]
[CsEvalRegistered(typeof(InvalidOperationException))]
[CsEvalRegistered(typeof(List<int>))]
[CsEvalRegistered(typeof(List<double>))]
[CsEvalRegistered(typeof(List<string>))]
[CsEvalRegistered(typeof(List<object>))]
[CsEvalRegistered(typeof(Dictionary<string, object>))]
[CsEvalRegistered(typeof(Dictionary<string, string>))]
[CsEvalRegistered(typeof(Dictionary<string, int>))]
[CsEvalRegistered(typeof(HashSet<int>))]
[CsEvalRegistered(typeof(HashSet<string>))]
[CsEvalRegistered(typeof(Queue<int>))]
[CsEvalRegistered(typeof(Queue<string>))]
[CsEvalRegistered(typeof(Stack<int>))]
[CsEvalRegistered(typeof(Stack<string>))]
[CsEvalRegistered(typeof(ValueTuple<int, int>))]
[CsEvalRegistered(typeof(ValueTuple<string, int>))]
[CsEvalRegistered(typeof(ValueTuple<string, string>))]
[CsEvalRegistered(typeof(ValueTuple<object, object>))]
[CsEvalRegistered(typeof(Nullable<int>))]
[CsEvalRegistered(typeof(Nullable<double>))]
[CsEvalRegistered(typeof(Nullable<bool>))]
[CsEvalRegistered(typeof(Nullable<long>))]
public partial class CsEvalBuiltInContext : CsEvalTypeContext;
