// <auto-generated by scripts/generate-fast-invokers.sh>
// Do not edit manually.

namespace Alder.Runtime;

internal static partial class MethodDispatchCache
{
    private static FastInvoker CreateStaticVoidInvoker0(MethodInfo method)
    {
        var d = (Action)method.CreateDelegate(typeof(Action));
        return (_, _) => { d(); return null; };
    }

    private static FastInvoker CreateStaticInvoker0<TResult>(MethodInfo method)
    {
        var d = (Func<TResult>)method.CreateDelegate(typeof(Func<TResult>));
        return (_, _) => d();
    }

    private static FastInvoker CreateInstanceVoidInvoker0<TTarget>(MethodInfo method)
    {
        var d = (Action<TTarget>)method.CreateDelegate(typeof(Action<TTarget>));
        return (target, _) => { d((TTarget)target!); return null; };
    }

    private static FastInvoker CreateInstanceInvoker0<TTarget, TResult>(MethodInfo method)
    {
        var d = (Func<TTarget, TResult>)method.CreateDelegate(typeof(Func<TTarget, TResult>));
        return (target, _) => d((TTarget)target!);
    }

    private static FastInvoker CreateStaticVoidInvoker1<T0>(MethodInfo method)
    {
        var d = (Action<T0>)method.CreateDelegate(typeof(Action<T0>));
        return (_, args) => { d((T0)args[0]!); return null; };
    }

    private static FastInvoker CreateStaticInvoker1<T0, TResult>(MethodInfo method)
    {
        var d = (Func<T0, TResult>)method.CreateDelegate(typeof(Func<T0, TResult>));
        return (_, args) => d((T0)args[0]!);
    }

    private static FastInvoker CreateInstanceVoidInvoker1<TTarget, T0>(MethodInfo method)
    {
        var d = (Action<TTarget, T0>)method.CreateDelegate(typeof(Action<TTarget, T0>));
        return (target, args) => { d((TTarget)target!, (T0)args[0]!); return null; };
    }

    private static FastInvoker CreateInstanceInvoker1<TTarget, T0, TResult>(MethodInfo method)
    {
        var d = (Func<TTarget, T0, TResult>)method.CreateDelegate(typeof(Func<TTarget, T0, TResult>));
        return (target, args) => d((TTarget)target!, (T0)args[0]!);
    }

    private static FastInvoker CreateStaticVoidInvoker2<T0, T1>(MethodInfo method)
    {
        var d = (Action<T0, T1>)method.CreateDelegate(typeof(Action<T0, T1>));
        return (_, args) => { d((T0)args[0]!, (T1)args[1]!); return null; };
    }

    private static FastInvoker CreateStaticInvoker2<T0, T1, TResult>(MethodInfo method)
    {
        var d = (Func<T0, T1, TResult>)method.CreateDelegate(typeof(Func<T0, T1, TResult>));
        return (_, args) => d((T0)args[0]!, (T1)args[1]!);
    }

    private static FastInvoker CreateInstanceVoidInvoker2<TTarget, T0, T1>(MethodInfo method)
    {
        var d = (Action<TTarget, T0, T1>)method.CreateDelegate(typeof(Action<TTarget, T0, T1>));
        return (target, args) => { d((TTarget)target!, (T0)args[0]!, (T1)args[1]!); return null; };
    }

    private static FastInvoker CreateInstanceInvoker2<TTarget, T0, T1, TResult>(MethodInfo method)
    {
        var d = (Func<TTarget, T0, T1, TResult>)method.CreateDelegate(typeof(Func<TTarget, T0, T1, TResult>));
        return (target, args) => d((TTarget)target!, (T0)args[0]!, (T1)args[1]!);
    }

    private static FastInvoker CreateStaticVoidInvoker3<T0, T1, T2>(MethodInfo method)
    {
        var d = (Action<T0, T1, T2>)method.CreateDelegate(typeof(Action<T0, T1, T2>));
        return (_, args) => { d((T0)args[0]!, (T1)args[1]!, (T2)args[2]!); return null; };
    }

    private static FastInvoker CreateStaticInvoker3<T0, T1, T2, TResult>(MethodInfo method)
    {
        var d = (Func<T0, T1, T2, TResult>)method.CreateDelegate(typeof(Func<T0, T1, T2, TResult>));
        return (_, args) => d((T0)args[0]!, (T1)args[1]!, (T2)args[2]!);
    }

    private static FastInvoker CreateInstanceVoidInvoker3<TTarget, T0, T1, T2>(MethodInfo method)
    {
        var d = (Action<TTarget, T0, T1, T2>)method.CreateDelegate(typeof(Action<TTarget, T0, T1, T2>));
        return (target, args) => { d((TTarget)target!, (T0)args[0]!, (T1)args[1]!, (T2)args[2]!); return null; };
    }

    private static FastInvoker CreateInstanceInvoker3<TTarget, T0, T1, T2, TResult>(MethodInfo method)
    {
        var d = (Func<TTarget, T0, T1, T2, TResult>)method.CreateDelegate(typeof(Func<TTarget, T0, T1, T2, TResult>));
        return (target, args) => d((TTarget)target!, (T0)args[0]!, (T1)args[1]!, (T2)args[2]!);
    }

    private static FastInvoker CreateStaticVoidInvoker4<T0, T1, T2, T3>(MethodInfo method)
    {
        var d = (Action<T0, T1, T2, T3>)method.CreateDelegate(typeof(Action<T0, T1, T2, T3>));
        return (_, args) => { d((T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!); return null; };
    }

    private static FastInvoker CreateStaticInvoker4<T0, T1, T2, T3, TResult>(MethodInfo method)
    {
        var d = (Func<T0, T1, T2, T3, TResult>)method.CreateDelegate(typeof(Func<T0, T1, T2, T3, TResult>));
        return (_, args) => d((T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!);
    }

    private static FastInvoker CreateInstanceVoidInvoker4<TTarget, T0, T1, T2, T3>(MethodInfo method)
    {
        var d = (Action<TTarget, T0, T1, T2, T3>)method.CreateDelegate(typeof(Action<TTarget, T0, T1, T2, T3>));
        return (target, args) => { d((TTarget)target!, (T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!); return null; };
    }

    private static FastInvoker CreateInstanceInvoker4<TTarget, T0, T1, T2, T3, TResult>(MethodInfo method)
    {
        var d = (Func<TTarget, T0, T1, T2, T3, TResult>)method.CreateDelegate(typeof(Func<TTarget, T0, T1, T2, T3, TResult>));
        return (target, args) => d((TTarget)target!, (T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!);
    }

    private static FastInvoker CreateStaticVoidInvoker5<T0, T1, T2, T3, T4>(MethodInfo method)
    {
        var d = (Action<T0, T1, T2, T3, T4>)method.CreateDelegate(typeof(Action<T0, T1, T2, T3, T4>));
        return (_, args) => { d((T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!); return null; };
    }

    private static FastInvoker CreateStaticInvoker5<T0, T1, T2, T3, T4, TResult>(MethodInfo method)
    {
        var d = (Func<T0, T1, T2, T3, T4, TResult>)method.CreateDelegate(typeof(Func<T0, T1, T2, T3, T4, TResult>));
        return (_, args) => d((T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!);
    }

    private static FastInvoker CreateInstanceVoidInvoker5<TTarget, T0, T1, T2, T3, T4>(MethodInfo method)
    {
        var d = (Action<TTarget, T0, T1, T2, T3, T4>)method.CreateDelegate(typeof(Action<TTarget, T0, T1, T2, T3, T4>));
        return (target, args) => { d((TTarget)target!, (T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!); return null; };
    }

    private static FastInvoker CreateInstanceInvoker5<TTarget, T0, T1, T2, T3, T4, TResult>(MethodInfo method)
    {
        var d = (Func<TTarget, T0, T1, T2, T3, T4, TResult>)method.CreateDelegate(typeof(Func<TTarget, T0, T1, T2, T3, T4, TResult>));
        return (target, args) => d((TTarget)target!, (T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!);
    }

    private static FastInvoker CreateStaticVoidInvoker6<T0, T1, T2, T3, T4, T5>(MethodInfo method)
    {
        var d = (Action<T0, T1, T2, T3, T4, T5>)method.CreateDelegate(typeof(Action<T0, T1, T2, T3, T4, T5>));
        return (_, args) => { d((T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!, (T5)args[5]!); return null; };
    }

    private static FastInvoker CreateStaticInvoker6<T0, T1, T2, T3, T4, T5, TResult>(MethodInfo method)
    {
        var d = (Func<T0, T1, T2, T3, T4, T5, TResult>)method.CreateDelegate(typeof(Func<T0, T1, T2, T3, T4, T5, TResult>));
        return (_, args) => d((T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!, (T5)args[5]!);
    }

    private static FastInvoker CreateInstanceVoidInvoker6<TTarget, T0, T1, T2, T3, T4, T5>(MethodInfo method)
    {
        var d = (Action<TTarget, T0, T1, T2, T3, T4, T5>)method.CreateDelegate(typeof(Action<TTarget, T0, T1, T2, T3, T4, T5>));
        return (target, args) => { d((TTarget)target!, (T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!, (T5)args[5]!); return null; };
    }

    private static FastInvoker CreateInstanceInvoker6<TTarget, T0, T1, T2, T3, T4, T5, TResult>(MethodInfo method)
    {
        var d = (Func<TTarget, T0, T1, T2, T3, T4, T5, TResult>)method.CreateDelegate(typeof(Func<TTarget, T0, T1, T2, T3, T4, T5, TResult>));
        return (target, args) => d((TTarget)target!, (T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!, (T5)args[5]!);
    }

    private static FastInvoker CreateStaticVoidInvoker7<T0, T1, T2, T3, T4, T5, T6>(MethodInfo method)
    {
        var d = (Action<T0, T1, T2, T3, T4, T5, T6>)method.CreateDelegate(typeof(Action<T0, T1, T2, T3, T4, T5, T6>));
        return (_, args) => { d((T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!, (T5)args[5]!, (T6)args[6]!); return null; };
    }

    private static FastInvoker CreateStaticInvoker7<T0, T1, T2, T3, T4, T5, T6, TResult>(MethodInfo method)
    {
        var d = (Func<T0, T1, T2, T3, T4, T5, T6, TResult>)method.CreateDelegate(typeof(Func<T0, T1, T2, T3, T4, T5, T6, TResult>));
        return (_, args) => d((T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!, (T5)args[5]!, (T6)args[6]!);
    }

    private static FastInvoker CreateInstanceVoidInvoker7<TTarget, T0, T1, T2, T3, T4, T5, T6>(MethodInfo method)
    {
        var d = (Action<TTarget, T0, T1, T2, T3, T4, T5, T6>)method.CreateDelegate(typeof(Action<TTarget, T0, T1, T2, T3, T4, T5, T6>));
        return (target, args) => { d((TTarget)target!, (T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!, (T5)args[5]!, (T6)args[6]!); return null; };
    }

    private static FastInvoker CreateInstanceInvoker7<TTarget, T0, T1, T2, T3, T4, T5, T6, TResult>(MethodInfo method)
    {
        var d = (Func<TTarget, T0, T1, T2, T3, T4, T5, T6, TResult>)method.CreateDelegate(typeof(Func<TTarget, T0, T1, T2, T3, T4, T5, T6, TResult>));
        return (target, args) => d((TTarget)target!, (T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!, (T5)args[5]!, (T6)args[6]!);
    }

    private static FastInvoker CreateStaticVoidInvoker8<T0, T1, T2, T3, T4, T5, T6, T7>(MethodInfo method)
    {
        var d = (Action<T0, T1, T2, T3, T4, T5, T6, T7>)method.CreateDelegate(typeof(Action<T0, T1, T2, T3, T4, T5, T6, T7>));
        return (_, args) => { d((T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!, (T5)args[5]!, (T6)args[6]!, (T7)args[7]!); return null; };
    }

    private static FastInvoker CreateStaticInvoker8<T0, T1, T2, T3, T4, T5, T6, T7, TResult>(MethodInfo method)
    {
        var d = (Func<T0, T1, T2, T3, T4, T5, T6, T7, TResult>)method.CreateDelegate(typeof(Func<T0, T1, T2, T3, T4, T5, T6, T7, TResult>));
        return (_, args) => d((T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!, (T5)args[5]!, (T6)args[6]!, (T7)args[7]!);
    }

    private static FastInvoker CreateInstanceVoidInvoker8<TTarget, T0, T1, T2, T3, T4, T5, T6, T7>(MethodInfo method)
    {
        var d = (Action<TTarget, T0, T1, T2, T3, T4, T5, T6, T7>)method.CreateDelegate(typeof(Action<TTarget, T0, T1, T2, T3, T4, T5, T6, T7>));
        return (target, args) => { d((TTarget)target!, (T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!, (T5)args[5]!, (T6)args[6]!, (T7)args[7]!); return null; };
    }

    private static FastInvoker CreateInstanceInvoker8<TTarget, T0, T1, T2, T3, T4, T5, T6, T7, TResult>(MethodInfo method)
    {
        var d = (Func<TTarget, T0, T1, T2, T3, T4, T5, T6, T7, TResult>)method.CreateDelegate(typeof(Func<TTarget, T0, T1, T2, T3, T4, T5, T6, T7, TResult>));
        return (target, args) => d((TTarget)target!, (T0)args[0]!, (T1)args[1]!, (T2)args[2]!, (T3)args[3]!, (T4)args[4]!, (T5)args[5]!, (T6)args[6]!, (T7)args[7]!);
    }

}
