<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alder\Alder.csproj" />
    <ProjectReference Include="..\Alder.Generators\Alder.Generators.csproj" PrivateAssets="all" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Compilation\BoundExpressionEmitter.Assignments.cs">
      <DependentUpon>BoundExpressionEmitter.cs</DependentUpon>
    </Compile>
    <Compile Update="Compilation\BoundExpressionEmitter.ControlFlow.cs">
      <DependentUpon>BoundExpressionEmitter.cs</DependentUpon>
    </Compile>
    <Compile Update="Compilation\BoundExpressionEmitter.Expressions.cs">
      <DependentUpon>BoundExpressionEmitter.cs</DependentUpon>
    </Compile>
    <Compile Update="Compilation\BoundExpressionEmitter.Invocations.cs">
      <DependentUpon>BoundExpressionEmitter.cs</DependentUpon>
    </Compile>
    <Compile Update="Compilation\BoundExpressionEmitter.Literals.cs">
      <DependentUpon>BoundExpressionEmitter.cs</DependentUpon>
    </Compile>
    <Compile Update="Compilation\BoundExpressionEmitter.LocalPromotion.cs">
      <DependentUpon>BoundExpressionEmitter.cs</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
