<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <PackageId>Alder.Compiled</PackageId>
    <Version>0.1.0-preview.1</Version>
    <Authors>Silvio Martignetti</Authors>
    <Description>Compilation engine that transforms Alder expressions into IL for near-native execution speed.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alder\Alder.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Compilation\BoundExpressionEmitter.Assignments.cs">
      <DependentUpon>BoundExpressionEmitter.cs</DependentUpon>
    </Compile>
    <Compile Update="Compilation\BoundExpressionEmitter.ControlFlow.cs">
      <DependentUpon>BoundExpressionEmitter.cs</DependentUpon>
    </Compile>
    <Compile Update="Compilation\BoundExpressionEmitter.Expressions.cs">
      <DependentUpon>BoundExpressionEmitter.cs</DependentUpon>
    </Compile>
    <Compile Update="Compilation\BoundExpressionEmitter.Invocations.cs">
      <DependentUpon>BoundExpressionEmitter.cs</DependentUpon>
    </Compile>
    <Compile Update="Compilation\BoundExpressionEmitter.Literals.cs">
      <DependentUpon>BoundExpressionEmitter.cs</DependentUpon>
    </Compile>
    <Compile Update="Compilation\BoundExpressionEmitter.LocalPromotion.cs">
      <DependentUpon>BoundExpressionEmitter.cs</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
