namespace Alder.Aot;

[AlderRegistered(typeof(int))]
[AlderRegistered(typeof(long))]
[AlderRegistered(typeof(double))]
[AlderRegistered(typeof(float))]
[AlderRegistered(typeof(decimal))]
[AlderRegistered(typeof(bool))]
[AlderRegistered(typeof(char))]
[AlderRegistered(typeof(byte))]
[AlderRegistered(typeof(string))]
[AlderRegistered(typeof(object))]
[AlderRegistered(typeof(DateTime))]
[AlderRegistered(typeof(TimeSpan))]
[AlderRegistered(typeof(Guid))]
[AlderRegistered(typeof(Math))]
[AlderRegistered(typeof(Convert))]
[AlderRegistered(typeof(Environment))]
[AlderRegistered(typeof(Exception))]
[AlderRegistered(typeof(ArgumentException))]
[AlderRegistered(typeof(ArgumentNullException))]
[AlderRegistered(typeof(InvalidOperationException))]
[AlderRegistered(typeof(Array))]
[AlderRegistered(typeof(System.Linq.Enumerable))]
[AlderRegistered(typeof(List<int>))]
[AlderRegistered(typeof(List<double>))]
[AlderRegistered(typeof(List<string>))]
[AlderRegistered(typeof(List<object>))]
[AlderRegistered(typeof(Dictionary<string, object>))]
[AlderRegistered(typeof(Dictionary<string, string>))]
[AlderRegistered(typeof(Dictionary<string, int>))]
[AlderRegistered(typeof(HashSet<int>))]
[AlderRegistered(typeof(HashSet<string>))]
[AlderRegistered(typeof(Queue<int>))]
[AlderRegistered(typeof(Queue<string>))]
[AlderRegistered(typeof(Stack<int>))]
[AlderRegistered(typeof(Stack<string>))]
[AlderRegistered(typeof(ValueTuple<int, int>))]
[AlderRegistered(typeof(ValueTuple<int, string>))]
[AlderRegistered(typeof(ValueTuple<int, double>))]
[AlderRegistered(typeof(ValueTuple<int, long>))]
[AlderRegistered(typeof(ValueTuple<int, bool>))]
[AlderRegistered(typeof(ValueTuple<string, int>))]
[AlderRegistered(typeof(ValueTuple<string, string>))]
[AlderRegistered(typeof(ValueTuple<bool, string>))]
[AlderRegistered(typeof(ValueTuple<double, double>))]
[AlderRegistered(typeof(ValueTuple<object, object>))]
[AlderRegistered(typeof(ValueTuple<int, int, int>))]
[AlderRegistered(typeof(ValueTuple<int, string, bool>))]
[AlderRegistered(typeof(ValueTuple<int, int, int, int>))]
[AlderRegistered(typeof(ValueTuple<int, int, int, int, int>))]
[AlderRegistered(typeof(ValueTuple<int, int, int, int, int, int>))]
[AlderRegistered(typeof(ValueTuple<int, int, int, int, int, int, int>))]
[AlderRegistered(typeof(Nullable<int>))]
[AlderRegistered(typeof(Nullable<double>))]
[AlderRegistered(typeof(Nullable<bool>))]
[AlderRegistered(typeof(Nullable<long>))]
public partial class AlderBuiltInContext : AlderTypeContext;
