namespace Alder.Aot;

/// <summary>
/// Provides AOT-generated metadata for a specific type, enabling reflection-free member access and method dispatch.
/// Implementations are generated by the Alder source generator.
/// </summary>
public interface IAotTypeMetadata
{
    /// <summary>
    /// Gets the .NET type described by this metadata.
    /// </summary>
    Type Type { get; }

    /// <summary>
    /// Attempts to read an instance property by name.
    /// </summary>
    /// <param name="name">The property name.</param>
    /// <param name="instance">The object instance.</param>
    /// <param name="value">When successful, the property value.</param>
    /// <returns><c>true</c> if the property was found and read; otherwise, <c>false</c>.</returns>
    bool TryGetProperty(string name, object instance, out object? value);

    /// <summary>
    /// Attempts to set an instance property by name.
    /// </summary>
    /// <param name="name">The property name.</param>
    /// <param name="instance">The object instance.</param>
    /// <param name="value">The value to set.</param>
    /// <returns><c>true</c> if the property was found and set; otherwise, <c>false</c>.</returns>
    bool TrySetProperty(string name, object instance, object? value);

    /// <summary>
    /// Attempts to read an instance field by name.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="instance">The object instance.</param>
    /// <param name="value">When successful, the field value.</param>
    /// <returns><c>true</c> if the field was found and read; otherwise, <c>false</c>.</returns>
    bool TryGetField(string name, object instance, out object? value);

    /// <summary>
    /// Attempts to set an instance field by name.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="instance">The object instance.</param>
    /// <param name="value">The value to set.</param>
    /// <returns><c>true</c> if the field was found and set; otherwise, <c>false</c>.</returns>
    bool TrySetField(string name, object instance, object? value);

    /// <summary>
    /// Attempts to read a value by index (e.g., <c>list[0]</c>).
    /// </summary>
    /// <param name="instance">The object instance.</param>
    /// <param name="key">The index key.</param>
    /// <param name="value">When successful, the indexed value.</param>
    /// <returns><c>true</c> if the indexed read succeeded; otherwise, <c>false</c>.</returns>
    bool TryGetIndex(object instance, object key, out object? value);

    /// <summary>
    /// Attempts to set a value by index (e.g., <c>list[0] = x</c>).
    /// </summary>
    /// <param name="instance">The object instance.</param>
    /// <param name="key">The index key.</param>
    /// <param name="value">The value to set.</param>
    /// <returns><c>true</c> if the indexed write succeeded; otherwise, <c>false</c>.</returns>
    bool TrySetIndex(object instance, object key, object? value);

    /// <summary>
    /// Attempts to read a static property by name.
    /// </summary>
    /// <param name="name">The property name.</param>
    /// <param name="value">When successful, the property value.</param>
    /// <returns><c>true</c> if the static property was found and read; otherwise, <c>false</c>.</returns>
    bool TryGetStaticProperty(string name, out object? value);

    /// <summary>
    /// Attempts to read a static field by name.
    /// </summary>
    /// <param name="name">The field name.</param>
    /// <param name="value">When successful, the field value.</param>
    /// <returns><c>true</c> if the static field was found and read; otherwise, <c>false</c>.</returns>
    bool TryGetStaticField(string name, out object? value);

    /// <summary>
    /// Attempts to create an instance of the type with the given constructor arguments.
    /// </summary>
    /// <param name="args">The constructor arguments.</param>
    /// <param name="instance">When successful, the created instance.</param>
    /// <returns><c>true</c> if construction succeeded; otherwise, <c>false</c>.</returns>
    bool TryCreateInstance(object?[] args, out object? instance);

    /// <summary>
    /// Attempts to invoke an instance method by name.
    /// </summary>
    /// <param name="name">The method name.</param>
    /// <param name="instance">The object instance.</param>
    /// <param name="args">The method arguments.</param>
    /// <param name="result">When successful, the return value (or <c>null</c> for void methods).</param>
    /// <returns><c>true</c> if the method was found and invoked; otherwise, <c>false</c>.</returns>
    bool TryInvokeMethod(string name, object instance, object?[] args, out object? result);

    /// <summary>
    /// Attempts to invoke a static method by name.
    /// </summary>
    /// <param name="name">The method name.</param>
    /// <param name="args">The method arguments.</param>
    /// <param name="result">When successful, the return value (or <c>null</c> for void methods).</param>
    /// <returns><c>true</c> if the static method was found and invoked; otherwise, <c>false</c>.</returns>
    bool TryInvokeStaticMethod(string name, object?[] args, out object? result);
}
