namespace Alder.Aot;

/// <summary>
/// Provides typed, reflection-free member access and method dispatch for a specific type.
/// Implementations are generated by the Alder source generator. The runtime checks typed dispatch
/// before falling back to reflection — this is the primary dispatch path for both JIT and AOT.
/// </summary>
public interface ITypedDispatch
{
    /// <summary>The .NET type described by this dispatch.</summary>
    Type Type { get; }

    /// <summary>Reads an instance member (property or field) by name.</summary>
    bool TryGet(string name, object instance, out object? value);

    /// <summary>Writes an instance member (property or field) by name.</summary>
    bool TrySet(string name, object instance, object? value);

    /// <summary>Reads a static member (property or field) by name.</summary>
    bool TryGetStatic(string name, out object? value);

    /// <summary>Reads a value by index (e.g., <c>list[0]</c>).</summary>
    bool TryGetIndex(object instance, object key, out object? value);

    /// <summary>Writes a value by index (e.g., <c>list[0] = x</c>).</summary>
    bool TrySetIndex(object instance, object key, object? value);

    /// <summary>Creates an instance of the type with the given constructor arguments.</summary>
    bool TryCreate(object?[] args, out object? instance);

    /// <summary>Invokes an instance method by name.</summary>
    bool TryInvoke(string name, object instance, object?[] args, out object? result);

    /// <summary>Invokes a static method by name.</summary>
    bool TryInvokeStatic(string name, object?[] args, out object? result);
}
