namespace Alder.Aot;

/// <summary>
/// Provides typed, reflection-free member access and method dispatch for a specific type.
/// Implementations are generated by the Alder source generator. The runtime checks typed dispatch
/// before falling back to reflection — this is the primary dispatch path for both JIT and AOT.
/// Subclasses override only the methods their type actually needs; the base returns false for everything.
/// </summary>
public abstract class TypedDispatch
{
    /// <summary>The .NET type described by this dispatch.</summary>
    public abstract Type Type { get; }

    /// <summary>Reads an instance member (property or field) by name.</summary>
    public virtual bool TryGet(string name, object instance, out object? value) { value = default; return false; }

    /// <summary>Writes an instance member (property or field) by name.</summary>
    public virtual bool TrySet(string name, object instance, object? value) => false;

    /// <summary>Reads a static member (property or field) by name.</summary>
    public virtual bool TryGetStatic(string name, out object? value) { value = default; return false; }

    /// <summary>Reads a value by index (e.g., <c>list[0]</c>).</summary>
    public virtual bool TryGetIndex(object instance, object key, out object? value) { value = default; return false; }

    /// <summary>Writes a value by index (e.g., <c>list[0] = x</c>).</summary>
    public virtual bool TrySetIndex(object instance, object key, object? value) => false;

    /// <summary>Creates an instance of the type with the given constructor arguments.</summary>
    public virtual bool TryCreate(object?[] args, out object? instance) { instance = default; return false; }

    /// <summary>Invokes an instance method by name.</summary>
    public virtual bool TryInvoke(string name, object instance, object?[] args, out object? result) { result = default; return false; }

    /// <summary>Invokes a static method by name.</summary>
    public virtual bool TryInvokeStatic(string name, object?[] args, out object? result) { result = default; return false; }
}
