<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CA1822</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Evaluation\Evaluator.Helpers.cs">
      <DependentUpon>Evaluator.cs</DependentUpon>
    </Compile>
    <Compile Update="Evaluation\Evaluator.Linq.cs">
      <DependentUpon>Evaluator.cs</DependentUpon>
    </Compile>
    <Compile Update="Evaluation\Evaluator.Loops.cs">
      <DependentUpon>Evaluator.cs</DependentUpon>
    </Compile>
    <Compile Update="Evaluation\Evaluator.Switch.cs">
      <DependentUpon>Evaluator.cs</DependentUpon>
    </Compile>
    <Compile Update="Evaluation\Evaluator.TypeCoercion.cs">
      <DependentUpon>Evaluator.cs</DependentUpon>
    </Compile>
    <Compile Update="Parsing\Parser.Expressions.cs">
      <DependentUpon>Parser.cs</DependentUpon>
    </Compile>
    <Compile Update="Parsing\Parser.Primary.cs">
      <DependentUpon>Parser.cs</DependentUpon>
    </Compile>
    <Compile Update="Parsing\Parser.Statements.cs">
      <DependentUpon>Parser.cs</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
