<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CA1822</NoWarn>
    <PackageId>CsEval</PackageId>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootDescriptor Include="Runtime/roots.xml" />
  </ItemGroup>

</Project>
