<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <PackageId>CsEval.Compiled</PackageId>
    <Description>Optional compiled backend package for CsEval.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CsEval\CsEval.csproj" />
  </ItemGroup>

</Project>
