#!/usr/bin/env bash
# Generates the mechanical factory methods in LambdaDelegateFactory.cs.
# These methods exist because AOT requires concrete generic instantiations at each arity.
# Run: ./scripts/generate-delegate-factories.sh > src/Alder/Runtime/LambdaDelegateFactory.generated.cs
set -euo pipefail

MAX_FUNC=16  # BCL Func<> max arity (Func<T1,...,T16,TResult>)
MAX_ACTION=16 # BCL Action<> max arity (Action<T1,...,T16>)

# Helpers
type_params() { local n=$1; for ((i=0; i<n; i++)); do [[ $i -gt 0 ]] && printf ", "; printf "T%d" "$i"; done; }
type_params_with_result() { local n=$1; local tp; tp=$(type_params "$n"); [[ -n "$tp" ]] && printf "%s, TResult" "$tp" || printf "TResult"; }
arg_params() { local n=$1; for ((i=0; i<n; i++)); do [[ $i -gt 0 ]] && printf ", "; printf "T%d arg%d" "$i" "$i"; done; }
arg_list() { local n=$1; for ((i=0; i<n; i++)); do [[ $i -gt 0 ]] && printf ", "; printf "arg%d" "$i"; done; }

cat <<'HEADER'
// <auto-generated by scripts/generate-delegate-factories.sh>
// Do not edit manually. Regenerate with: ./scripts/generate-delegate-factories.sh

namespace Alder.Runtime;

internal static partial class LambdaDelegateFactory
{
HEADER

# Compiled Action factories
for ((n=0; n<=MAX_ACTION; n++)); do
    tp=$(type_params "$n")
    ap=$(arg_params "$n")
    al=$(arg_list "$n")
    generic=""; [[ -n "$tp" ]] && generic="<$tp>"
    if ((n <= 2)); then
        invoke="MethodInvoker.InvokeCompiledLambda${n}(lambda$([ -n "$al" ] && echo ", $al"))"
    else
        invoke="MethodInvoker.InvokeCompiledLambda(lambda, [$al])"
    fi
    echo "    private static Delegate CreateCompiledAction${n}${generic}(CompiledLambdaValue lambda) =>"
    echo "        new Action${generic}(($ap) => _ = $invoke);"
    echo
done

# Compiled Func factories
for ((n=0; n<=MAX_FUNC; n++)); do
    tp=$(type_params_with_result "$n")
    ap=$(arg_params "$n")
    al=$(arg_list "$n")
    generic="<$tp>"
    if ((n <= 2)); then
        invoke="MethodInvoker.InvokeCompiledLambda${n}(lambda$([ -n "$al" ] && echo ", $al"))"
    else
        invoke="MethodInvoker.InvokeCompiledLambda(lambda, [$al])"
    fi
    echo "    private static Delegate CreateCompiledFunc${n}${generic}(CompiledLambdaValue lambda) =>"
    echo "        new Func${generic}(($ap) => CastResult<TResult>($invoke));"
    echo
done

# Interpreted Action factories
for ((n=0; n<=MAX_ACTION; n++)); do
    tp=$(type_params "$n")
    ap=$(arg_params "$n")
    al=$(arg_list "$n")
    generic=""; [[ -n "$tp" ]] && generic="<$tp>"
    args_expr="EmptyArgs"
    ((n > 0)) && args_expr="[$al]"
    echo "    private static Delegate CreateInterpretedAction${n}${generic}(LambdaValue lambda) =>"
    echo "        new Action${generic}(($ap) => _ = MethodInvoker.InvokeLambda(lambda, $args_expr, lambda.Closure));"
    echo
done

# Interpreted Func factories
for ((n=0; n<=MAX_FUNC; n++)); do
    tp=$(type_params_with_result "$n")
    ap=$(arg_params "$n")
    al=$(arg_list "$n")
    generic="<$tp>"
    args_expr="EmptyArgs"
    ((n > 0)) && args_expr="[$al]"
    echo "    private static Delegate CreateInterpretedFunc${n}${generic}(LambdaValue lambda) =>"
    echo "        new Func${generic}(($ap) => CastResult<TResult>(MethodInvoker.InvokeLambda(lambda, $args_expr, lambda.Closure)));"
    echo
done

echo "}"
