using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Alder.Generators.Model;

namespace Alder.Generators.Emitters;

/// <summary>
/// Generates AOT delegate factories derived from the actual delegate types
/// that appear as parameters in expanded method models. No hardcoded shapes.
/// </summary>
internal static class DelegateFactoryEmitter
{
    public static string? Emit(
        ImmutableArray<TypeRegistrationModel> registrations,
        ImmutableArray<DelegateSignature> extensionDelegates = default)
    {
        var valueTypeNames = CollectValueTypeNames(registrations);
        var delegateTypes = CollectDelegateTypes(registrations, valueTypeNames, extensionDelegates);
        if (delegateTypes.Count == 0)
            return null;

        var w = new SourceWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine("#nullable enable");
        w.AppendLine("#pragma warning disable CS8600, CS8603, CS8605");
        w.AppendLine();

        var invoke = "global::Alder.Aot.GeneratedCodeHelpers.InvokeLambda";
        var lv = "object"; // Lambda is passed as object; the facade handles the cast

        using (w.Block("file static class AotDelegateFactories"))
        {
            using (w.Block("internal static global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Func<object, global::System.Delegate>> Create()"))
            {
                w.AppendLine("var d = new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Func<object, global::System.Delegate>>();");

                foreach (var dt in delegateTypes)
                    EmitFactory(w, dt, invoke, lv);

                w.AppendLine("return d;");
            }
        }

        return w.ToString();
    }

    /// <summary>
    /// Scans all expanded methods across all registrations for Func/Action parameter types
    /// where the first generic argument is a registered value type. These are the delegate
    /// types that need AOT factories for NativeAOT lambda conversion.
    /// </summary>
    private static List<DelegateTypeInfo> CollectDelegateTypes(
        ImmutableArray<TypeRegistrationModel> registrations,
        List<string> valueTypeNames,
        ImmutableArray<DelegateSignature> extensionDelegates = default)
    {
        var valueTypeSet = new HashSet<string>(valueTypeNames);
        var seen = new HashSet<string>();
        var result = new List<DelegateTypeInfo>();

        // Collect delegate types from expanded methods using Roslyn-extracted signatures.
        foreach (var reg in registrations)
        {
            foreach (var method in reg.Methods)
            {
                foreach (var param in method.Parameters)
                {
                    if (param.DelegateInfo is { } sig && seen.Add(param.TypeFullName))
                        result.Add(new DelegateTypeInfo(param.TypeFullName, sig.ParamTypes.ToArray(), sig.ReturnType, sig.IsAction));
                }
            }
        }

        // Merge delegate shapes from extension method dispatch emitter
        if (!extensionDelegates.IsDefaultOrEmpty)
        {
            foreach (var sig in extensionDelegates)
            {
                var typeName = sig.IsAction
                    ? $"global::System.Action<{string.Join(", ", sig.ParamTypes)}>"
                    : $"global::System.Func<{string.Join(", ", sig.ParamTypes)}{(sig.ParamTypes.Length > 0 ? ", " : "")}{sig.ReturnType}>";
                if (seen.Add(typeName))
                    result.Add(new DelegateTypeInfo(typeName, sig.ParamTypes.ToArray(), sig.ReturnType, sig.IsAction));
            }
        }

        // Comparison<T> for value types (used by Sort, not always in method params)
        foreach (var vt in valueTypeNames)
        {
            var compType = $"global::System.Comparison<{vt}>";
            if (seen.Add(compType))
                result.Add(new DelegateTypeInfo(compType, new[] { vt, vt }, "int", false));
        }

        // Func<T> (zero-arg) for value types, needed for Func<int> f = () => 42 and similar
        // variable assignments that don't appear as method parameters.
        // Reference-type Func<T> (Func<string>, Func<Customer>) use MakeGenericMethod at runtime.
        foreach (var vt in valueTypeNames)
        {
            var funcType = $"global::System.Func<{vt}>";
            if (seen.Add(funcType))
                result.Add(new DelegateTypeInfo(funcType, System.Array.Empty<string>(), vt, false));
        }

        return result;
    }

    private static void EmitFactory(SourceWriter w, DelegateTypeInfo dt, string invoke, string lv)
    {
        var paramList = string.Join(", ", dt.ParamTypes.Select((p, i) => $"{p} arg{i}"));
        var argArray = string.Join(", ", dt.ParamTypes.Select((_, i) => $"arg{i}"));
        var call = $"{invoke}(l, new object?[] {{ {argArray} }})";

        var castResult = "global::Alder.Aot.GeneratedCodeHelpers.CastResult";
        var body = dt.IsAction
            ? $"{{ {call}; }}"
            : $"{castResult}<{dt.ReturnType}>({call})";

        w.AppendLine($"d[typeof({dt.FullTypeName})] = l => new {dt.FullTypeName}(({paramList}) => {body});");
    }

    internal static List<string> CollectValueTypeNames(ImmutableArray<TypeRegistrationModel> registrations)
    {
        var seen = new HashSet<string>();
        var result = new List<string>();

        foreach (var reg in registrations)
        {
            if (reg.IsValueType && !reg.IsClosedGeneric && seen.Add(reg.TypeFullName))
                result.Add(reg.TypeFullName);
        }

        return result;
    }

    private readonly struct DelegateTypeInfo
    {
        public readonly string FullTypeName;
        public readonly string[] ParamTypes;
        public readonly string ReturnType;
        public readonly bool IsAction;

        public DelegateTypeInfo(string fullTypeName, string[] paramTypes, string returnType, bool isAction)
        {
            FullTypeName = fullTypeName;
            ParamTypes = paramTypes;
            ReturnType = returnType;
            IsAction = isAction;
        }

        public bool HasValueTypeArg(HashSet<string> valueTypes)
        {
            return ParamTypes.Length > 0 && valueTypes.Contains(ParamTypes[0]);
        }
    }
}
