using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Alder.Generators.Model;

namespace Alder.Generators.Emitters;

internal static class DelegateFactoryEmitter
{
    private static readonly string[] CommonDelegateShapes =
    [
        "global::System.Func<{0}, bool>",
        "global::System.Func<{0}, {0}>",
        "global::System.Func<{0}, int>",
        "global::System.Func<{0}, global::System.Int32>",
        "global::System.Func<{0}, string>",
        "global::System.Func<{0}, global::System.String>",
        "global::System.Func<{0}, object>",
        "global::System.Func<{0}, global::System.Object>",
        "global::System.Action<{0}>",
        "global::System.Comparison<{0}>",
    ];

    public static string? Emit(ImmutableArray<TypeRegistrationModel> registrations)
    {
        var valueTypes = CollectValueTypeNames(registrations);
        if (valueTypes.Count == 0)
            return null;

        var w = new SourceWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine("#nullable enable");
        w.AppendLine("#pragma warning disable CS8600, CS8603, CS8605");
        w.AppendLine();

        using (w.Block("file static class AotDelegateFactories"))
        {
            using (w.Block("internal static global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Func<object, global::System.Delegate>> Create()"))
            {
                w.AppendLine("var d = new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Func<object, global::System.Delegate>>();");

                foreach (var vt in valueTypes)
                    EmitFactoriesForType(w, vt);

                w.AppendLine("return d;");
            }
        }

        return w.ToString();
    }

    private static void EmitFactoriesForType(SourceWriter w, string typeFullName)
    {
        // Func<T, bool> — predicates (Where, Any, All, First, etc.)
        EmitFuncFactory(w, typeFullName, "bool", 1);
        // Func<T, T> — identity transforms (Select, etc.)
        EmitFuncFactory(w, typeFullName, typeFullName, 1);
        // Func<T, int> — int projections
        EmitFuncFactory(w, typeFullName, "int", 1);
        // Func<T, string> — string projections
        EmitFuncFactory(w, typeFullName, "string", 1);
        // Func<T, object> — boxing projections
        EmitFuncFactory(w, typeFullName, "object", 1);
        // Action<T> — ForEach, side effects
        EmitActionFactory(w, typeFullName, 1);
        // Func<T, T, T> — Aggregate
        EmitFuncFactory(w, typeFullName, typeFullName, 2, typeFullName);
        // Func<T, T, bool> — comparison predicates
        EmitFuncFactory(w, typeFullName, "bool", 2, typeFullName);
        // Comparison<T> — Sort
        EmitComparisonFactory(w, typeFullName);
    }

    private static void EmitFuncFactory(SourceWriter w, string argType, string returnType, int arity, string? arg2Type = null)
    {
        var delegateType = arity switch
        {
            1 => $"global::System.Func<{argType}, {returnType}>",
            2 => $"global::System.Func<{argType}, {arg2Type}, {returnType}>",
            _ => null
        };
        if (delegateType == null) return;

        var args = arity switch
        {
            1 => $"({argType} arg0) => (({returnType})global::Alder.Runtime.MethodInvoker.InvokeLambda((global::Alder.Runtime.LambdaValue)l, new object?[] {{ arg0 }}, ((global::Alder.Runtime.LambdaValue)l).Closure)!)",
            2 => $"({argType} arg0, {arg2Type} arg1) => (({returnType})global::Alder.Runtime.MethodInvoker.InvokeLambda((global::Alder.Runtime.LambdaValue)l, new object?[] {{ arg0, arg1 }}, ((global::Alder.Runtime.LambdaValue)l).Closure)!)",
            _ => null
        };
        if (args == null) return;

        w.AppendLine($"d[typeof({delegateType})] = l => new {delegateType}({args});");
    }

    private static void EmitActionFactory(SourceWriter w, string argType, int arity)
    {
        var delegateType = $"global::System.Action<{argType}>";
        w.AppendLine($"d[typeof({delegateType})] = l => new {delegateType}(({argType} arg0) => {{ global::Alder.Runtime.MethodInvoker.InvokeLambda((global::Alder.Runtime.LambdaValue)l, new object?[] {{ arg0 }}, ((global::Alder.Runtime.LambdaValue)l).Closure); }});");
    }

    private static void EmitComparisonFactory(SourceWriter w, string argType)
    {
        var delegateType = $"global::System.Comparison<{argType}>";
        w.AppendLine($"d[typeof({delegateType})] = l => new {delegateType}(({argType} arg0, {argType} arg1) => ((int)global::Alder.Runtime.MethodInvoker.InvokeLambda((global::Alder.Runtime.LambdaValue)l, new object?[] {{ arg0, arg1 }}, ((global::Alder.Runtime.LambdaValue)l).Closure)!));");
    }

    internal static List<string> CollectValueTypeNames(ImmutableArray<TypeRegistrationModel> registrations)
    {
        var valueTypeKeywords = new HashSet<string>
        {
            "int", "global::System.Int32",
            "long", "global::System.Int64",
            "double", "global::System.Double",
            "float", "global::System.Single",
            "decimal", "global::System.Decimal",
            "bool", "global::System.Boolean",
            "char", "global::System.Char",
            "byte", "global::System.Byte",
            "short", "global::System.Int16",
            "ushort", "global::System.UInt16",
            "uint", "global::System.UInt32",
            "ulong", "global::System.UInt64",
            "sbyte", "global::System.SByte",
        };

        var seen = new HashSet<string>();
        var result = new List<string>();

        foreach (var reg in registrations)
        {
            if (valueTypeKeywords.Contains(reg.TypeFullName) && seen.Add(reg.TypeFullName))
                result.Add(reg.TypeFullName);
        }

        return result;
    }
}
