using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Alder.Generators.Model;

namespace Alder.Generators.Emitters;

/// <summary>
/// Generates AOT delegate factories derived from the actual delegate types
/// that appear as parameters in expanded method models. No hardcoded shapes.
/// </summary>
internal static class DelegateFactoryEmitter
{
    public static string? Emit(ImmutableArray<TypeRegistrationModel> registrations)
    {
        var valueTypeNames = CollectValueTypeNames(registrations);
        if (valueTypeNames.Count == 0)
            return null;

        // Collect all unique delegate parameter types from expanded methods
        // where the delegate's first type argument is a value type.
        var delegateTypes = CollectDelegateTypes(registrations, valueTypeNames);
        if (delegateTypes.Count == 0)
            return null;

        var w = new SourceWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine("#nullable enable");
        w.AppendLine("#pragma warning disable CS8600, CS8603, CS8605");
        w.AppendLine();

        var invoke = "global::Alder.Runtime.MethodInvoker.InvokeLambda";
        var lv = "global::Alder.Runtime.LambdaValue";

        using (w.Block("file static class AotDelegateFactories"))
        {
            using (w.Block("internal static global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Func<object, global::System.Delegate>> Create()"))
            {
                w.AppendLine("var d = new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Func<object, global::System.Delegate>>();");

                foreach (var dt in delegateTypes)
                    EmitFactory(w, dt, invoke, lv);

                w.AppendLine("return d;");
            }
        }

        return w.ToString();
    }

    /// <summary>
    /// Scans all expanded methods across all registrations for Func/Action parameter types
    /// where the first generic argument is a registered value type. These are the delegate
    /// types that need AOT factories for NativeAOT lambda conversion.
    /// </summary>
    private static List<DelegateTypeInfo> CollectDelegateTypes(
        ImmutableArray<TypeRegistrationModel> registrations,
        List<string> valueTypeNames)
    {
        var valueTypeSet = new HashSet<string>(valueTypeNames);
        var seen = new HashSet<string>();
        var result = new List<DelegateTypeInfo>();

        foreach (var reg in registrations)
        {
            foreach (var method in reg.Methods)
            {
                foreach (var param in method.Parameters)
                {
                    if (TryParseDelegateType(param.TypeFullName, out var info) &&
                        info.HasValueTypeArg(valueTypeSet) &&
                        seen.Add(info.FullTypeName))
                    {
                        result.Add(info);
                    }
                }
            }
        }

        // Also add Comparison<T> for each value type (used by Sort, not always in method params)
        foreach (var vt in valueTypeNames)
        {
            var compType = $"global::System.Comparison<{vt}>";
            if (seen.Add(compType))
                result.Add(new DelegateTypeInfo(compType, new[] { vt, vt }, "int", false));
        }

        return result;
    }

    private static bool TryParseDelegateType(string typeName, out DelegateTypeInfo info)
    {
        info = default;

        // Parse "global::System.Func<A, B, C>" or "global::System.Action<A>"
        var funcPrefix = "global::System.Func<";
        var actionPrefix = "global::System.Action<";

        string inner;
        bool isAction;

        if (typeName.StartsWith(funcPrefix) && typeName.EndsWith(">"))
        {
            inner = typeName.Substring(funcPrefix.Length, typeName.Length - funcPrefix.Length - 1);
            isAction = false;
        }
        else if (typeName.StartsWith(actionPrefix) && typeName.EndsWith(">"))
        {
            inner = typeName.Substring(actionPrefix.Length, typeName.Length - actionPrefix.Length - 1);
            isAction = true;
        }
        else
        {
            return false;
        }

        // Split by ", " but respect nested generics
        var args = SplitGenericArgs(inner);
        if (args.Length == 0) return false;

        if (isAction)
        {
            info = new DelegateTypeInfo(typeName, args, "void", true);
        }
        else
        {
            // Last arg is return type for Func
            var paramArgs = new string[args.Length - 1];
            System.Array.Copy(args, paramArgs, paramArgs.Length);
            var returnType = args[args.Length - 1];
            info = new DelegateTypeInfo(typeName, paramArgs, returnType, false);
        }
        return true;
    }

    private static string[] SplitGenericArgs(string inner)
    {
        var result = new List<string>();
        var depth = 0;
        var start = 0;

        for (var i = 0; i < inner.Length; i++)
        {
            if (inner[i] == '<') depth++;
            else if (inner[i] == '>') depth--;
            else if (inner[i] == ',' && depth == 0)
            {
                result.Add(inner.Substring(start, i - start).Trim());
                start = i + 1;
            }
        }
        result.Add(inner.Substring(start).Trim());
        return result.ToArray();
    }

    private static void EmitFactory(SourceWriter w, DelegateTypeInfo dt, string invoke, string lv)
    {
        var paramList = string.Join(", ", dt.ParamTypes.Select((p, i) => $"{p} arg{i}"));
        var argArray = string.Join(", ", dt.ParamTypes.Select((_, i) => $"arg{i}"));
        var call = $"{invoke}(({lv})l, new object?[] {{ {argArray} }}, (({lv})l).Closure)";

        var body = dt.IsAction
            ? $"{{ {call}; }}"
            : $"(({dt.ReturnType}){call}!)";

        w.AppendLine($"d[typeof({dt.FullTypeName})] = l => new {dt.FullTypeName}(({paramList}) => {body});");
    }

    internal static List<string> CollectValueTypeNames(ImmutableArray<TypeRegistrationModel> registrations)
    {
        var seen = new HashSet<string>();
        var result = new List<string>();

        foreach (var reg in registrations)
        {
            if (reg.IsValueType && !reg.IsClosedGeneric && seen.Add(reg.TypeFullName))
                result.Add(reg.TypeFullName);
        }

        return result;
    }

    private readonly struct DelegateTypeInfo
    {
        public readonly string FullTypeName;
        public readonly string[] ParamTypes;
        public readonly string ReturnType;
        public readonly bool IsAction;

        public DelegateTypeInfo(string fullTypeName, string[] paramTypes, string returnType, bool isAction)
        {
            FullTypeName = fullTypeName;
            ParamTypes = paramTypes;
            ReturnType = returnType;
            IsAction = isAction;
        }

        public bool HasValueTypeArg(HashSet<string> valueTypes)
        {
            return ParamTypes.Length > 0 && valueTypes.Contains(ParamTypes[0]);
        }
    }
}
