using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Alder.Generators.Model;

namespace Alder.Generators.Emitters;

/// <summary>
/// Emits generated dispatch for supported LINQ extension methods.
/// This covers collection shapes that NativeAOT cannot close reliably at runtime.
/// </summary>
internal static class ExtensionDispatchEmitter
{
    // Enumerable exposes dedicated numeric aggregate overloads only for these element types.
    private static readonly HashSet<string> NumericSumTypes = new() { "int", "long", "double", "float", "decimal" };

    public static (string? Source, ImmutableArray<DelegateSignature> DelegateShapes) Emit(
        ImmutableArray<TypeRegistrationModel> registrations,
        ImmutableArray<ExtensionMethodModel> extensionMethods)
    {
        var valueTypes = DelegateFactoryEmitter.CollectValueTypeNames(registrations);
        if (valueTypes.Count == 0 || extensionMethods.IsDefaultOrEmpty)
            return (null, ImmutableArray<DelegateSignature>.Empty);

        // Add common reference types that appear in LINQ selectors and projections even when no registered type roots them.
        var dispatchTypes = new List<string>(valueTypes) { "string", "object" };

        var delegateShapes = new List<DelegateSignature>();
        var w = new SourceWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine("#nullable enable");
        w.AppendLine("#pragma warning disable CS8600, CS8602, CS8603, CS8604, CS8605");
        w.AppendLine();

        using (w.Block("file sealed class LinqValueTypeDispatch : global::Alder.Aot.TypedDispatch"))
        {
            w.AppendLine("public override global::System.Type Type => typeof(global::System.Linq.Enumerable);");
            w.AppendLine();

            using (w.Block("public override bool TryInvokeStatic(string name, object?[] args, out object? result)"))
            {
                w.AppendLine("result = null;");
                w.AppendLine("if (args.Length < 1 || args[0] == null) return false;");
                w.AppendLine("var elementType = global::Alder.Aot.GeneratedCodeHelpers.GetEnumerableElementType(args[0].GetType());");
                w.AppendLine("if (elementType == null) return false;");
                w.AppendLine();

                foreach (var et in dispatchTypes)
                {
                    var id = TypeParser.SanitizeIdentifier(et);
                    w.AppendLine($"if (elementType == typeof({et})) return TryInvoke_{id}(name, args, out result);");
                }
                w.AppendLine("return false;");
            }

            foreach (var et in dispatchTypes)
            {
                w.AppendLine();
                EmitPerTypeDispatch(w, et, TypeParser.SanitizeIdentifier(et),
                    extensionMethods, dispatchTypes, delegateShapes);
            }
        }

        return (w.ToString(), delegateShapes.ToImmutableArray());
    }

    private static void EmitPerTypeDispatch(
        SourceWriter w, string vt, string id,
        ImmutableArray<ExtensionMethodModel> methods,
        List<string> dispatchTypes,
        List<DelegateSignature> delegateShapes)
    {
        var ie = $"global::System.Collections.Generic.IEnumerable<{vt}>";
        var en = "global::System.Linq.Enumerable";

        var byName = methods.GroupBy(m => m.MethodName).OrderBy(g => g.Key);

        using (w.Block($"private static bool TryInvoke_{id}(string name, object?[] args, out object? result)"))
        {
            w.AppendLine("result = null;");
            using (w.Block("switch (name)"))
            {
                foreach (var group in byName)
                {
                    w.AppendLine($"case \"{group.Key}\":");
                    var overloads = group.ToList();

                    foreach (var overload in overloads)
                        EmitOverload(w, overload, vt, ie, en, dispatchTypes, delegateShapes);

                    w.AppendLine("    return false;");
                }
            }
            w.AppendLine("return false;");
        }
    }

    private static void EmitOverload(
        SourceWriter w, ExtensionMethodModel method,
        string vt, string ie, string en,
        List<string> dispatchTypes,
        List<DelegateSignature> delegateShapes)
    {
        switch (method.Kind)
        {
            case ExtensionMethodKind.NoArg:
                if (IsNumericAggregate(method.MethodName) && !NumericSumTypes.Contains(vt))
                    break;
                w.AppendLine($"    if (args.Length == 1) {{ result = {en}.{method.MethodName}(({ie})args[0]!); return true; }}");
                break;

            case ExtensionMethodKind.SingleDelegate:
                EmitDelegateOverload(w, method, vt, ie, en, dispatchTypes, delegateShapes);
                break;

            case ExtensionMethodKind.SingleValue:
                EmitValueOverload(w, method, vt, ie, en);
                break;

            case ExtensionMethodKind.SingleEnumerable:
                w.AppendLine($"    if (args.Length == 2 && args[1] is {ie} e_{method.MethodName}) {{ result = {en}.{method.MethodName}(({ie})args[0]!, e_{method.MethodName}); return true; }}");
                break;

            case ExtensionMethodKind.Complex:
                break;
        }
    }

    private static void EmitDelegateOverload(
        SourceWriter w, ExtensionMethodModel method,
        string vt, string ie, string en,
        List<string> dispatchTypes,
        List<DelegateSignature> delegateShapes)
    {
        if (method.ExtraParams.Length != 1 || method.ExtraParams[0].DelegateInfo is not { } sig)
            return;

        if (sig.ParamTypes.Length == 1 && sig.ReturnType is "bool" or "global::System.Boolean")
        {
            var funcType = $"global::System.Func<{vt}, bool>";
            TrackDelegate(delegateShapes, vt, "bool");
            var varName = $"d_{method.MethodName}";
            w.AppendLine($"    if (args.Length == 2 && args[1] is {funcType} {varName}) {{ result = {en}.{method.MethodName}(({ie})args[0]!, {varName}); return true; }}");
            return;
        }

        if (sig.ParamTypes.Length == 1)
        {
            if (IsNumericAggregate(method.MethodName))
            {
                w.AppendLine("    if (args.Length == 2)");
                w.AppendLine("    {");
                foreach (var numType in NumericSumTypes)
                {
                    var funcType = $"global::System.Func<{vt}, {numType}>";
                    TrackDelegate(delegateShapes, vt, numType);
                    var varName = $"d_{method.MethodName}_{TypeParser.SanitizeIdentifier(numType)}";
                    w.AppendLine($"        if (args[1] is {funcType} {varName}) {{ result = {en}.{method.MethodName}(({ie})args[0]!, {varName}); return true; }}");
                }
                w.AppendLine("    }");
                return;
            }

            w.AppendLine("    if (args.Length == 2)");
            w.AppendLine("    {");
            foreach (var rt in dispatchTypes)
            {
                var funcType = $"global::System.Func<{vt}, {rt}>";
                TrackDelegate(delegateShapes, vt, rt);
                var varName = $"d_{method.MethodName}_{TypeParser.SanitizeIdentifier(rt)}";
                w.AppendLine($"        if (args[1] is {funcType} {varName}) {{ result = {en}.{method.MethodName}(({ie})args[0]!, {varName}); return true; }}");
            }
            w.AppendLine("    }");
            return;
        }
    }

    private static void EmitValueOverload(
        SourceWriter w, ExtensionMethodModel method,
        string vt, string ie, string en)
    {
        if (method.ExtraParams.Length != 1)
            return;

        var paramType = method.ExtraParams[0].TypePattern;

        if (paramType is "int" or "global::System.Int32")
        {
            var varName = $"v_{method.MethodName}";
            w.AppendLine($"    if (args.Length == 2 && args[1] is int {varName}) {{ result = {en}.{method.MethodName}(({ie})args[0]!, {varName}); return true; }}");
            return;
        }

        if (paramType.Contains(vt) || method.ExtraParams[0].IsTypeParameter)
        {
            var varName = $"v_{method.MethodName}";
            w.AppendLine($"    if (args.Length == 2 && args[1] is {vt} {varName}) {{ result = {en}.{method.MethodName}(({ie})args[0]!, {varName}); return true; }}");
        }
    }

    private static bool IsNumericAggregate(string methodName) =>
        methodName is "Sum" or "Average" or "LongCount";

    private static void TrackDelegate(List<DelegateSignature> shapes, string paramType, string returnType)
    {
        var sig = new DelegateSignature(
            ImmutableArray.Create(paramType),
            returnType,
            false);
        if (!shapes.Any(s => s.ParamTypes.SequenceEqual(sig.ParamTypes) && s.ReturnType == sig.ReturnType))
            shapes.Add(sig);
    }
}
