using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Alder.Generators.Model;

namespace Alder.Generators.Emitters;

internal static class ExtensionMethodEmitter
{
    private const string IE = "global::System.Collections.Generic.IEnumerable";
    private const string IOE = "global::System.Linq.IOrderedEnumerable";
    private const string Linq = "global::System.Linq.Enumerable";
    private static readonly string[] NumericTypes = { "int", "long", "double", "float", "decimal" };

    public static string? Emit(ImmutableArray<TypeRegistrationModel> registrations)
    {
        var valueTypes = DelegateFactoryEmitter.CollectValueTypeNames(registrations);
        if (valueTypes.Count == 0)
            return null;

        var w = new SourceWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine("#nullable enable");
        w.AppendLine("#pragma warning disable CS8600, CS8602, CS8603, CS8604, CS8605");
        w.AppendLine();

        using (w.Block("file sealed class EnumerableDispatch : global::Alder.Aot.ITypedDispatch"))
        {
            w.AppendLine($"public global::System.Type Type => typeof({Linq});");
            w.AppendLine();
            EmitStubs(w);
            w.AppendLine();
            EmitLambdaConverters(w);
            w.AppendLine();
            EmitTryInvokeStatic(w, valueTypes);
        }

        return w.ToString();
    }

    private static void EmitStubs(SourceWriter w)
    {
        w.AppendLine("public bool TryGet(string name, object instance, out object? value) { value = null; return false; }");
        w.AppendLine("public bool TrySet(string name, object instance, object? value) { return false; }");
        w.AppendLine("public bool TryGetStatic(string name, out object? value) { value = null; return false; }");
        w.AppendLine("public bool TryGetIndex(object instance, object key, out object? value) { value = null; return false; }");
        w.AppendLine("public bool TrySetIndex(object instance, object key, object? value) { return false; }");
        w.AppendLine("public bool TryCreate(object?[] args, out object? instance) { instance = null; return false; }");
        w.AppendLine("public bool TryInvoke(string name, object instance, object?[] args, out object? result) { result = null; return false; }");
    }

    private static void EmitLambdaConverters(SourceWriter w)
    {
        var lv = "global::Alder.Runtime.LambdaValue";
        var invoke = "global::Alder.Runtime.MethodInvoker.InvokeLambda";

        w.AppendLine("private static global::System.Func<T, bool>? AsPredicate<T>(object? arg)");
        using (w.Block())
        {
            w.AppendLine("if (arg is global::System.Func<T, bool> f) return f;");
            w.AppendLine($"if (arg is {lv} lv && lv.Parameters.Count == 1) return (T a) => (bool){invoke}(lv, new object?[] {{ a }}, lv.Closure)!;");
            w.AppendLine("return null;");
        }

        w.AppendLine("private static global::System.Func<T, TResult>? AsFunc<T, TResult>(object? arg)");
        using (w.Block())
        {
            w.AppendLine("if (arg is global::System.Func<T, TResult> f) return f;");
            w.AppendLine("return null;");
        }

        w.AppendLine("private static global::System.Func<T1, T2, TResult>? AsFunc2<T1, T2, TResult>(object? arg)");
        using (w.Block())
        {
            w.AppendLine("if (arg is global::System.Func<T1, T2, TResult> f) return f;");
            w.AppendLine("return null;");
        }

        w.AppendLine("private static global::System.Func<T, object?>? AsProjection<T>(object? arg)");
        using (w.Block())
        {
            w.AppendLine("#if NET7_0_OR_GREATER");
            w.AppendLine("if (global::System.Runtime.CompilerServices.RuntimeFeature.IsDynamicCodeSupported) return null;");
            w.AppendLine("#else");
            w.AppendLine("return null;");
            w.AppendLine("#endif");
            w.AppendLine("if (arg is global::System.Func<T, object?> f) return f;");
            w.AppendLine($"if (arg is {lv} lv && lv.Parameters.Count == 1) return (T a) => {invoke}(lv, new object?[] {{ a }}, lv.Closure);");
            w.AppendLine("return null;");
        }
    }

    private static void EmitTryInvokeStatic(SourceWriter w, List<string> valueTypes)
    {
        using (w.Block("public bool TryInvokeStatic(string name, object?[] args, out object? result)"))
        {
            using (w.Block("switch (name)"))
            {
                // Range is a special case — not generic, fixed (int, int) → IEnumerable<int>
                EmitRangeCase(w);

                foreach (var desc in LinqMethodDescriptor.All)
                {
                    w.AppendLine($"case \"{desc.Name}\":");
                    w.Indent();

                    if (desc.AlsoParameterless)
                        EmitParameterlessOverload(w, desc.Name, valueTypes);

                    EmitShape(w, desc, valueTypes);

                    if (desc.AlsoFilter)
                        EmitFilterOverload(w, desc.Name, valueTypes);

                    w.AppendLine("break;");
                    w.Outdent();
                }

                w.AppendLine("default: break;");
            }
            w.AppendLine("result = null;");
            w.AppendLine("return false;");
        }
    }

    private static void EmitShape(SourceWriter w, LinqMethodDescriptor desc, List<string> valueTypes)
    {
        switch (desc.Shape)
        {
            case LinqMethodShape.Parameterless:
                EmitParameterlessOverload(w, desc.Name, valueTypes);
                break;
            case LinqMethodShape.Filter:
                EmitFilterOverload(w, desc.Name, valueTypes);
                break;
            case LinqMethodShape.Projection:
                EmitProjectionOverload(w, desc.Name, valueTypes);
                break;
            case LinqMethodShape.OrderedProjection:
                EmitOrderedProjectionOverload(w, desc.Name, valueTypes);
                break;
            case LinqMethodShape.TwoSequence:
                EmitTwoSequenceOverload(w, desc.Name, valueTypes);
                break;
            case LinqMethodShape.IntArg:
                EmitIntArgOverload(w, desc.Name, valueTypes);
                break;
            case LinqMethodShape.ValueArg:
                EmitValueArgOverload(w, desc.Name, valueTypes);
                break;
            case LinqMethodShape.ScalarAggregate:
                EmitScalarAggregateOverload(w, desc.Name, desc.NumericOnly ? NumericTypes : valueTypes.ToArray());
                break;
            case LinqMethodShape.SeedAggregate:
                EmitSeedAggregateOverload(w, desc.Name, valueTypes);
                break;
            case LinqMethodShape.Generation:
                EmitGenerationOverload(w, desc.Name, valueTypes);
                break;
            case LinqMethodShape.SelectMany:
                EmitSelectManyOverload(w, valueTypes);
                break;
        }
    }

    // ── Shape emitters ──────────────────────────────────────────────

    private static void EmitParameterlessOverload(SourceWriter w, string method, List<string> valueTypes)
    {
        w.AppendLine("if (args.Length == 1)");
        using (w.Block())
        {
            foreach (var vt in AllTypes(valueTypes))
                EmitEnumerableCall1(w, method, vt);
        }
    }

    private static void EmitFilterOverload(SourceWriter w, string method, List<string> valueTypes)
    {
        w.AppendLine("if (args.Length == 2)");
        using (w.Block())
        {
            foreach (var vt in AllTypes(valueTypes))
            {
                var s = Safe(vt);
                w.AppendLine($"if (args[0] is {IE}<{vt}> {method.ToLower()}_s_{s} && AsPredicate<{vt}>(args[1]) is {{ }} {method.ToLower()}_p_{s})");
                w.AppendLine($"{{ result = {Linq}.{method}({method.ToLower()}_s_{s}, {method.ToLower()}_p_{s}); return true; }}");
            }
        }
    }

    private static void EmitProjectionOverload(SourceWriter w, string method, List<string> valueTypes)
    {
        var resultTypes = new[] { "int", "string", "bool", "object" };

        w.AppendLine("if (args.Length == 2)");
        using (w.Block())
        {
            foreach (var vt in valueTypes)
            {
                var s = Safe(vt);
                EmitFuncVariant(w, method, vt, vt, $"{s}_{s}");
                foreach (var rt in resultTypes)
                {
                    if (rt != vt)
                        EmitFuncVariant(w, method, vt, rt, $"{s}_{Safe(rt)}");
                }
            }
            EmitFuncVariant(w, method, "string", "string", "str_str");
            EmitFuncVariant(w, method, "string", "int", "str_i");
            EmitFuncVariant(w, method, "string", "bool", "str_b");
            EmitFuncVariant(w, method, "string", "object", "str_o");
            EmitFuncVariant(w, method, "object", "object", "obj_o");

            foreach (var vt in AllTypes(valueTypes))
                EmitProjectionFallback(w, method, vt);
        }
    }

    private static void EmitOrderedProjectionOverload(SourceWriter w, string method, List<string> valueTypes)
    {
        w.AppendLine("if (args.Length == 2)");
        using (w.Block())
        {
            foreach (var vt in valueTypes)
            {
                var s = Safe(vt);
                w.AppendLine($"if (args[0] is {IOE}<{vt}> {method.ToLower()}_s_{s} && AsFunc<{vt}, {vt}>(args[1]) is {{ }} {method.ToLower()}_f_{s})");
                w.AppendLine($"{{ result = {Linq}.{method}({method.ToLower()}_s_{s}, {method.ToLower()}_f_{s}); return true; }}");
            }

            foreach (var vt in valueTypes)
            {
                var s = Safe(vt);
                w.AppendLine($"if (args[0] is {IOE}<{vt}> {method.ToLower()}_lf_{s} && AsProjection<{vt}>(args[1]) is {{ }} {method.ToLower()}_lp_{s})");
                w.AppendLine($"{{ result = {Linq}.{method}({method.ToLower()}_lf_{s}, {method.ToLower()}_lp_{s}); return true; }}");
            }
        }
    }

    private static void EmitTwoSequenceOverload(SourceWriter w, string method, List<string> valueTypes)
    {
        w.AppendLine("if (args.Length == 2)");
        using (w.Block())
        {
            foreach (var vt in AllTypes(valueTypes))
            {
                var s = Safe(vt);
                w.AppendLine($"if (args[0] is {IE}<{vt}> {method.ToLower()}_a_{s} && args[1] is {IE}<{vt}> {method.ToLower()}_b_{s})");
                w.AppendLine($"{{ result = {Linq}.{method}({method.ToLower()}_a_{s}, {method.ToLower()}_b_{s}); return true; }}");
            }
        }
    }

    private static void EmitIntArgOverload(SourceWriter w, string method, List<string> valueTypes)
    {
        w.AppendLine("if (args.Length == 2 && args[1] is int)");
        using (w.Block())
        {
            foreach (var vt in AllTypes(valueTypes))
            {
                var s = Safe(vt);
                w.AppendLine($"if (args[0] is {IE}<{vt}> {method.ToLower()}_{s}) {{ result = {Linq}.{method}({method.ToLower()}_{s}, (int)args[1]!); return true; }}");
            }
        }
    }

    private static void EmitValueArgOverload(SourceWriter w, string method, List<string> valueTypes)
    {
        w.AppendLine("if (args.Length == 2)");
        using (w.Block())
        {
            foreach (var vt in AllTypes(valueTypes))
            {
                var s = Safe(vt);
                w.AppendLine($"if (args[0] is {IE}<{vt}> {method.ToLower()}_s_{s} && args[1] is {vt} {method.ToLower()}_v_{s})");
                w.AppendLine($"{{ result = {Linq}.{method}({method.ToLower()}_s_{s}, {method.ToLower()}_v_{s}); return true; }}");
            }
        }
    }

    private static void EmitScalarAggregateOverload(SourceWriter w, string method, string[] types)
    {
        w.AppendLine("if (args.Length == 1)");
        using (w.Block())
        {
            foreach (var vt in types)
            {
                var s = Safe(vt);
                w.AppendLine($"if (args[0] is {IE}<{vt}> {method.ToLower()}_{s}) {{ result = {Linq}.{method}({method.ToLower()}_{s}); return true; }}");
            }
        }
    }

    private static void EmitSeedAggregateOverload(SourceWriter w, string method, List<string> valueTypes)
    {
        w.AppendLine("if (args.Length == 2)");
        using (w.Block())
        {
            foreach (var vt in valueTypes)
            {
                var s = Safe(vt);
                w.AppendLine($"if (args[0] is {IE}<{vt}> {method.ToLower()}_s_{s} && AsFunc2<{vt}, {vt}, {vt}>(args[1]) is {{ }} {method.ToLower()}_f_{s})");
                w.AppendLine($"{{ result = {Linq}.{method}({method.ToLower()}_s_{s}, {method.ToLower()}_f_{s}); return true; }}");
            }
        }
    }

    private static void EmitGenerationOverload(SourceWriter w, string method, List<string> valueTypes)
    {
        w.AppendLine("if (args.Length == 2 && args[1] is int)");
        using (w.Block())
        {
            foreach (var vt in valueTypes)
            {
                var s = Safe(vt);
                w.AppendLine($"if (args[0] is {vt} {method.ToLower()}_{s}) {{ result = {Linq}.{method}({method.ToLower()}_{s}, (int)args[1]!); return true; }}");
            }
            w.AppendLine($"if (args[0] is string {method.ToLower()}_str) {{ result = {Linq}.{method}({method.ToLower()}_str, (int)args[1]!); return true; }}");
            w.AppendLine($"if (args[0] != null) {{ result = {Linq}.{method}(args[0], (int)args[1]!); return true; }}");
        }
    }

    private static void EmitSelectManyOverload(SourceWriter w, List<string> valueTypes)
    {
        w.AppendLine("if (args.Length == 2)");
        using (w.Block())
        {
            foreach (var vt in valueTypes)
            {
                var s = Safe(vt);
                EmitSelectManyVariant(w, vt, vt, $"{s}_{s}");
                EmitSelectManyVariant(w, vt, "object", $"{s}_o");
            }
            EmitSelectManyVariant(w, "string", "string", "str_str");
            EmitSelectManyVariant(w, "string", "object", "str_o");
            EmitSelectManyVariant(w, "object", "object", "obj_o");

            foreach (var vt in AllTypes(valueTypes))
                EmitSelectManyFallback(w, vt);
        }
    }

    private static void EmitRangeCase(SourceWriter w)
    {
        w.AppendLine("case \"Range\":");
        w.Indent();
        w.AppendLine("if (args.Length == 2 && args[0] is int range_start && args[1] is int range_count)");
        w.AppendLine($"{{ result = {Linq}.Range(range_start, range_count); return true; }}");
        w.AppendLine("break;");
        w.Outdent();
    }

    // ── Helpers ──────────────────────────────────────────────────────

    private static void EmitEnumerableCall1(SourceWriter w, string method, string vt)
    {
        var s = Safe(vt);
        w.AppendLine($"if (args[0] is {IE}<{vt}> {method.ToLower()}_{s})");
        w.AppendLine($"{{ result = {Linq}.{method}({method.ToLower()}_{s}); return true; }}");
    }

    private static void EmitFuncVariant(SourceWriter w, string method, string sourceType, string resultType, string varId)
    {
        w.AppendLine($"if (args[0] is {IE}<{sourceType}> {method.ToLower()}_s_{varId} && AsFunc<{sourceType}, {resultType}>(args[1]) is {{ }} {method.ToLower()}_f_{varId})");
        w.AppendLine($"{{ result = {Linq}.{method}({method.ToLower()}_s_{varId}, {method.ToLower()}_f_{varId}); return true; }}");
    }

    private static void EmitProjectionFallback(SourceWriter w, string method, string sourceType)
    {
        var s = Safe(sourceType);
        w.AppendLine($"if (args[0] is {IE}<{sourceType}> {method.ToLower()}_lf_{s} && AsProjection<{sourceType}>(args[1]) is {{ }} {method.ToLower()}_lp_{s})");
        w.AppendLine($"{{ result = {Linq}.{method}({method.ToLower()}_lf_{s}, {method.ToLower()}_lp_{s}); return true; }}");
    }

    private static void EmitSelectManyVariant(SourceWriter w, string sourceType, string resultType, string varId)
    {
        w.AppendLine($"if (args[0] is {IE}<{sourceType}> sm_s_{varId} && AsFunc<{sourceType}, {IE}<{resultType}>>(args[1]) is {{ }} sm_f_{varId})");
        w.AppendLine($"{{ result = {Linq}.SelectMany(sm_s_{varId}, sm_f_{varId}); return true; }}");
    }

    private static void EmitSelectManyFallback(SourceWriter w, string sourceType)
    {
        var s = Safe(sourceType);
        w.AppendLine($"if (args[0] is {IE}<{sourceType}> sm_lf_{s} && AsProjection<{sourceType}>(args[1]) is {{ }} sm_lp_{s})");
        using (w.Block())
        {
            w.AppendLine($"result = {Linq}.SelectMany(sm_lf_{s}, x =>");
            using (w.Block())
            {
                w.AppendLine($"var r = sm_lp_{s}(x);");
                w.AppendLine($"if (r is global::System.Collections.IEnumerable ie) return {Linq}.Cast<object>(ie);");
                w.AppendLine($"return {Linq}.Empty<object>();");
            }
            w.AppendLine(");");
            w.AppendLine("return true;");
        }
    }

    private static IEnumerable<string> AllTypes(List<string> valueTypes)
    {
        foreach (var vt in valueTypes)
            yield return vt;
        yield return "string";
        yield return "object";
    }

    private static string Safe(string typeName) => AlderSourceGenerator.SanitizeIdentifier(typeName);
}
