using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Alder.Generators.Model;

namespace Alder.Generators.Emitters;

internal static class TypeMetadataEmitter
{
    public static string Emit(TypeRegistrationModel reg)
    {
        var w = new SourceWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine("#nullable enable");
        w.AppendLine();

        using (w.Block($"file sealed class {reg.MetadataClassName} : global::Alder.Aot.IAotTypeMetadata"))
        {
            w.AppendLine($"public global::System.Type Type => typeof({reg.TypeFullName});");
            w.AppendLine();

            EmitTryGetProperty(w, reg);
            EmitTrySetProperty(w, reg);
            EmitTryGetField(w, reg);
            EmitTrySetField(w, reg);
            EmitTryGetIndex(w, reg);
            EmitTrySetIndex(w, reg);
            EmitTryGetStaticProperty(w, reg);
            EmitTryGetStaticField(w, reg);
            EmitTryCreateInstance(w, reg);
            EmitTryInvokeMethod(w, reg);
            EmitTryInvokeStaticMethod(w, reg);
        }

        return w.ToString();
    }

    public static string? EmitGenericInstantiations(ImmutableArray<TypeRegistrationModel> registrations)
    {
        var closedGenerics = registrations.Where(r => r.IsClosedGeneric).ToArray();
        if (closedGenerics.Length == 0)
            return null;

        var w = new SourceWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine("#nullable enable");
        w.AppendLine();

        using (w.Block("file static class GenericInstantiations"))
        {
            var seenFields = new HashSet<string>();
            foreach (var reg in closedGenerics)
            {
                var fieldName = "_" + SanitizeFieldName(reg.TypeFullName);
                if (!seenFields.Add(fieldName))
                    continue;
                w.AppendLine($"static readonly global::System.Type {fieldName} = typeof({reg.TypeFullName});");
            }
        }

        return w.ToString();
    }

    #region Property/Field accessors

    private static void EmitTryGetProperty(SourceWriter w, TypeRegistrationModel reg)
    {
        var members = reg.Properties.Where(p => p is { IsStatic: false, CanRead: true }).ToArray();
        EmitNameSwitch(w,
            "public bool TryGetProperty(string name, object instance, out object? value)",
            reg.TypeFullName,
            members.Select(p => (p.Name, $"value = typed.{p.Name}; return true;")).ToArray(),
            "value = default;", "return false;");
    }

    private static void EmitTrySetProperty(SourceWriter w, TypeRegistrationModel reg)
    {
        var members = reg.Properties.Where(p => p is { IsStatic: false, CanWrite: true }).ToArray();
        EmitNameSwitch(w,
            "public bool TrySetProperty(string name, object instance, object? value)",
            reg.TypeFullName,
            members.Select(p => (p.Name, $"typed.{p.Name} = ({p.TypeFullName})value!; return true;")).ToArray(),
            "return false;");
    }

    private static void EmitTryGetField(SourceWriter w, TypeRegistrationModel reg)
    {
        var members = reg.Fields.Where(f => !f.IsStatic).ToArray();
        EmitNameSwitch(w,
            "public bool TryGetField(string name, object instance, out object? value)",
            reg.TypeFullName,
            members.Select(f => (f.Name, $"value = typed.{f.Name}; return true;")).ToArray(),
            "value = default;", "return false;");
    }

    private static void EmitTrySetField(SourceWriter w, TypeRegistrationModel reg)
    {
        var members = reg.Fields.Where(f => f is { IsStatic: false, IsReadOnly: false }).ToArray();
        EmitNameSwitch(w,
            "public bool TrySetField(string name, object instance, object? value)",
            reg.TypeFullName,
            members.Select(f => (f.Name, $"typed.{f.Name} = ({f.TypeFullName})value!; return true;")).ToArray(),
            "return false;");
    }

    private static void EmitTryGetStaticProperty(SourceWriter w, TypeRegistrationModel reg)
    {
        var members = reg.Properties.Where(p => p is { IsStatic: true, CanRead: true }).ToArray();
        EmitNameSwitch(w,
            "public bool TryGetStaticProperty(string name, out object? value)",
            null,
            members.Select(p => (p.Name, $"value = {reg.TypeFullName}.{p.Name}; return true;")).ToArray(),
            "value = default;", "return false;");
    }

    private static void EmitTryGetStaticField(SourceWriter w, TypeRegistrationModel reg)
    {
        var members = reg.Fields.Where(f => f.IsStatic).ToArray();
        EmitNameSwitch(w,
            "public bool TryGetStaticField(string name, out object? value)",
            null,
            members.Select(f => (f.Name, $"value = {reg.TypeFullName}.{f.Name}; return true;")).ToArray(),
            "value = default;", "return false;");
    }

    #endregion

    #region Indexers

    private static void EmitTryGetIndex(SourceWriter w, TypeRegistrationModel reg)
    {
        var readable = reg.Indexers.Where(i => i.CanRead).ToArray();

        using (w.Block("public bool TryGetIndex(object instance, object key, out object? value)"))
        {
            if (readable.Length > 0)
            {
                var idx = readable[0];
                w.AppendLine($"value = (({reg.TypeFullName})instance)[({idx.KeyTypeFullName})key];");
                w.AppendLine("return true;");
            }
            else
            {
                w.AppendLine("value = default;");
                w.AppendLine("return false;");
            }
        }
        w.AppendLine();
    }

    private static void EmitTrySetIndex(SourceWriter w, TypeRegistrationModel reg)
    {
        var writable = reg.Indexers.Where(i => i.CanWrite).ToArray();

        using (w.Block("public bool TrySetIndex(object instance, object key, object? value)"))
        {
            if (writable.Length > 0)
            {
                var idx = writable[0];
                w.AppendLine($"(({reg.TypeFullName})instance)[({idx.KeyTypeFullName})key] = ({idx.ValueTypeFullName})value!;");
                w.AppendLine("return true;");
            }
            else
            {
                w.AppendLine("return false;");
            }
        }
        w.AppendLine();
    }

    #endregion

    #region Constructors

    private static void EmitTryCreateInstance(SourceWriter w, TypeRegistrationModel reg)
    {
        using (w.Block("public bool TryCreateInstance(object?[] args, out object? instance)"))
        {
            if (reg.Constructors.Length > 0)
            {
                using (w.Block("switch (args.Length)"))
                {
                    foreach (var arityGroup in reg.Constructors.GroupBy(c => c.Parameters.Length).OrderBy(g => g.Key))
                    {
                        var ctors = arityGroup.ToArray();
                        w.AppendLine($"case {arityGroup.Key}:");
                        w.Indent();

                        if (arityGroup.Key == 0)
                        {
                            w.AppendLine($"instance = new {reg.TypeFullName}(); return true;");
                        }
                        else if (ctors.Length == 1)
                        {
                            var castArgs = FormatCastArgs(ctors[0].Parameters);
                            w.AppendLine($"instance = new {reg.TypeFullName}({castArgs}); return true;");
                        }
                        else
                        {
                            foreach (var ctor in ctors)
                            {
                                var condition = FormatTypeChecks(ctor.Parameters);
                                var castArgs = FormatCastArgs(ctor.Parameters);
                                w.AppendLine($"if ({condition}) {{ instance = new {reg.TypeFullName}({castArgs}); return true; }}");
                            }
                            w.AppendLine("instance = default; return false;");
                        }

                        w.Outdent();
                    }

                    w.AppendLine("default: instance = default; return false;");
                }
            }
            else
            {
                w.AppendLine("instance = default;");
                w.AppendLine("return false;");
            }
        }
    }

    #endregion

    #region Method invocation

    private static void EmitTryInvokeMethod(SourceWriter w, TypeRegistrationModel reg)
    {
        var methods = reg.Methods.Where(m => !m.IsStatic).ToArray();
        w.AppendLine();
        EmitMethodDispatch(w,
            "public bool TryInvokeMethod(string name, object instance, object?[] args, out object? result)",
            reg.TypeFullName, methods, isStatic: false);
    }

    private static void EmitTryInvokeStaticMethod(SourceWriter w, TypeRegistrationModel reg)
    {
        var methods = reg.Methods.Where(m => m.IsStatic).ToArray();
        w.AppendLine();
        EmitMethodDispatch(w,
            "public bool TryInvokeStaticMethod(string name, object?[] args, out object? result)",
            reg.TypeFullName, methods, isStatic: true);
    }

    #endregion

    #region Shared helpers

    /// <summary>
    /// Emits the repeated pattern: method signature → if members: typed cast + switch(name) { cases }; else: default return.
    /// </summary>
    private static void EmitNameSwitch(
        SourceWriter w,
        string signature,
        string? typedCastType,
        (string Name, string Body)[] cases,
        params string[] defaultStatements)
    {
        using (w.Block(signature))
        {
            if (cases.Length > 0)
            {
                if (typedCastType != null)
                    w.AppendLine($"var typed = ({typedCastType})instance;");

                using (w.Block("switch (name)"))
                {
                    foreach (var (name, body) in cases)
                        w.AppendLine($"case \"{name}\": {body}");
                    w.AppendLine($"default: {string.Join(" ", defaultStatements)}");
                }
            }
            else
            {
                foreach (var stmt in defaultStatements)
                    w.AppendLine(stmt);
            }
        }
        w.AppendLine();
    }

    /// <summary>
    /// Emits method dispatch with nested switch: name → args.Length → type-checked overloads.
    /// </summary>
    private static void EmitMethodDispatch(
        SourceWriter w,
        string signature,
        string typeFullName,
        MethodModel[] methods,
        bool isStatic)
    {
        var target = isStatic ? typeFullName : "typed";

        using (w.Block(signature))
        {
            if (methods.Length > 0)
            {
                if (!isStatic)
                    w.AppendLine($"var typed = ({typeFullName})instance;");

                using (w.Block("switch (name)"))
                {
                    foreach (var nameGroup in methods.GroupBy(m => m.Name))
                    {
                        w.AppendLine($"case \"{nameGroup.Key}\":");
                        w.Indent();

                        using (w.Block("switch (args.Length)"))
                        {
                            foreach (var arityGroup in nameGroup.GroupBy(m => m.Parameters.Length))
                            {
                                var overloads = arityGroup.ToArray();
                                w.AppendLine($"case {arityGroup.Key}:");
                                w.Indent();

                                if (overloads.Length == 1)
                                {
                                    EmitMethodCall(w, overloads[0], target);
                                }
                                else
                                {
                                    EmitOverloadDispatch(w, overloads, target);
                                }

                                w.AppendLine("break;");
                                w.Outdent();
                            }

                            w.AppendLine("default: break;");
                        }

                        w.AppendLine("break;");
                        w.Outdent();
                    }
                }

                w.AppendLine("result = default;");
                w.AppendLine("return false;");
            }
            else
            {
                w.AppendLine("result = default;");
                w.AppendLine("return false;");
            }
        }
    }

    private static void EmitMethodCall(SourceWriter w, MethodModel method, string target)
    {
        var castArgs = FormatCastArgs(method.Parameters);
        var call = $"{target}.{method.Name}({castArgs})";

        if (method.ReturnsVoid)
            w.AppendLine($"{call}; result = null; return true;");
        else
            w.AppendLine($"result = {call}; return true;");
    }

    private static void EmitOverloadDispatch(SourceWriter w, MethodModel[] methods, string target)
    {
        foreach (var method in methods)
        {
            var condition = FormatTypeChecks(method.Parameters);
            var castArgs = FormatCastArgs(method.Parameters);
            var call = $"{target}.{method.Name}({castArgs})";

            if (method.ReturnsVoid)
                w.AppendLine($"if ({condition}) {{ {call}; result = null; return true; }}");
            else
                w.AppendLine($"if ({condition}) {{ result = {call}; return true; }}");
        }
    }

    private static string FormatCastArgs(ImmutableArray<ParameterModel> parameters)
    {
        return string.Join(", ", parameters.Select((p, i) => $"({p.TypeFullName})args[{i}]!"));
    }

    private static string FormatTypeChecks(ImmutableArray<ParameterModel> parameters)
    {
        return string.Join(" && ", parameters.Select((p, i) => $"args[{i}] is {p.TypeFullName}"));
    }

    private static string SanitizeFieldName(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }
        var result = sb.ToString();
        if (result.StartsWith("global__"))
            result = result.Substring("global__".Length);
        return result;
    }

    #endregion
}
