using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Alder.Generators.Model;

namespace Alder.Generators.Emitters;

internal static class TypeMetadataEmitter
{
    public static string Emit(TypeRegistrationModel reg)
    {
        var w = new SourceWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine("#nullable enable");
        w.AppendLine();

        using (w.Block($"file sealed class {reg.MetadataClassName} : global::Alder.Aot.TypedDispatch"))
        {
            w.AppendLine($"public override global::System.Type Type => typeof({reg.TypeFullName});");

            EmitTryGetIfNeeded(w, reg);
            EmitTrySetIfNeeded(w, reg);
            EmitTryGetStaticIfNeeded(w, reg);
            EmitTryGetIndexIfNeeded(w, reg);
            EmitTrySetIndexIfNeeded(w, reg);
            EmitTryCreateIfNeeded(w, reg);
            EmitTryInvokeIfNeeded(w, reg);
            EmitTryInvokeStaticIfNeeded(w, reg);
        }

        return w.ToString();
    }

    public static string? EmitTypeRoots(ImmutableArray<TypeRegistrationModel> registrations)
    {
        var closedGenerics = registrations.Where(r => r.IsClosedGeneric).ToArray();
        var valueTypes = DelegateFactoryEmitter.CollectValueTypeNames(registrations);

        if (closedGenerics.Length == 0 && valueTypes.Count == 0)
            return null;

        var w = new SourceWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine("#nullable enable");
        w.AppendLine("#pragma warning disable CS8600, CS8602, CS8603, CS8604");
        w.AppendLine();

        using (w.Block("file static class TypeRoots"))
        {
            var seenFields = new HashSet<string>();

            foreach (var reg in closedGenerics)
            {
                var fieldName = "_" + TypeParser.SanitizeIdentifier(reg.TypeFullName);
                if (!seenFields.Add(fieldName))
                    continue;
                w.AppendLine($"static readonly global::System.Type {fieldName} = typeof({reg.TypeFullName});");
            }

            foreach (var vt in valueTypes)
            {
                var id = TypeParser.SanitizeIdentifier(vt);
                EmitTypeRoot(w, seenFields, $"Nullable_{id}", $"global::System.Nullable<{vt}>");
                EmitTypeRoot(w, seenFields, $"EqComparer_{id}", $"global::System.Collections.Generic.EqualityComparer<{vt}>");
                EmitTypeRoot(w, seenFields, $"Comparer_{id}", $"global::System.Collections.Generic.Comparer<{vt}>");
                EmitTypeRoot(w, seenFields, $"List_{id}", $"global::System.Collections.Generic.List<{vt}>");
                EmitTypeRoot(w, seenFields, $"IEnumerable_{id}", $"global::System.Collections.Generic.IEnumerable<{vt}>");
            }
        }

        return w.ToString();
    }

    private static void EmitTypeRoot(SourceWriter w, HashSet<string> seen, string fieldName, string typeFullName)
    {
        if (!seen.Add(fieldName))
            return;
        w.AppendLine($"static readonly global::System.Type _{fieldName} = typeof({typeFullName});");
    }

    #region Member accessors — only emitted when the type has matching members

    private static void EmitTryGetIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        var properties = reg.Properties.Where(p => p is { IsStatic: false, CanRead: true })
            .Select(p => (p.Name, $"value = typed.{p.Name}; return true;"));
        var fields = reg.Fields.Where(f => !f.IsStatic)
            .Select(f => (f.Name, $"value = typed.{f.Name}; return true;"));
        var cases = properties.Concat(fields).ToArray();

        if (cases.Length == 0) return;

        w.AppendLine();
        using (w.Block("public override bool TryGet(string name, object instance, out object? value)"))
        {
            w.AppendLine($"var typed = ({reg.TypeFullName})instance;");
            using (w.Block("switch (name)"))
            {
                foreach (var (name, body) in cases)
                    w.AppendLine($"case \"{name}\": {body}");
                w.AppendLine("default: value = default; return false;");
            }
        }
    }

    private static void EmitTrySetIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        var properties = reg.Properties.Where(p => p is { IsStatic: false, CanWrite: true })
            .Select(p => (p.Name, $"typed.{p.Name} = ({p.TypeFullName})value!; return true;"));
        var fields = reg.Fields.Where(f => f is { IsStatic: false, IsReadOnly: false })
            .Select(f => (f.Name, $"typed.{f.Name} = ({f.TypeFullName})value!; return true;"));
        var cases = properties.Concat(fields).ToArray();

        if (cases.Length == 0) return;

        w.AppendLine();
        using (w.Block("public override bool TrySet(string name, object instance, object? value)"))
        {
            w.AppendLine($"var typed = ({reg.TypeFullName})instance;");
            using (w.Block("switch (name)"))
            {
                foreach (var (name, body) in cases)
                    w.AppendLine($"case \"{name}\": {body}");
                w.AppendLine("default: return false;");
            }
        }
    }

    private static void EmitTryGetStaticIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        var properties = reg.Properties.Where(p => p is { IsStatic: true, CanRead: true })
            .Select(p => (p.Name, $"value = {reg.TypeFullName}.{p.Name}; return true;"));
        var fields = reg.Fields.Where(f => f.IsStatic)
            .Select(f => (f.Name, $"value = {reg.TypeFullName}.{f.Name}; return true;"));
        var cases = properties.Concat(fields).ToArray();

        if (cases.Length == 0) return;

        w.AppendLine();
        using (w.Block("public override bool TryGetStatic(string name, out object? value)"))
        {
            using (w.Block("switch (name)"))
            {
                foreach (var (name, body) in cases)
                    w.AppendLine($"case \"{name}\": {body}");
                w.AppendLine("default: value = default; return false;");
            }
        }
    }

    #endregion

    #region Indexers — only emitted when the type has indexers

    private static void EmitTryGetIndexIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        var readable = reg.Indexers.Where(i => i.CanRead).ToArray();
        if (readable.Length == 0) return;

        var idx = readable[0];
        w.AppendLine();
        using (w.Block("public override bool TryGetIndex(object instance, object key, out object? value)"))
        {
            w.AppendLine($"value = (({reg.TypeFullName})instance)[({idx.KeyTypeFullName})key];");
            w.AppendLine("return true;");
        }
    }

    private static void EmitTrySetIndexIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        var writable = reg.Indexers.Where(i => i.CanWrite).ToArray();
        if (writable.Length == 0) return;

        var idx = writable[0];
        w.AppendLine();
        using (w.Block("public override bool TrySetIndex(object instance, object key, object? value)"))
        {
            w.AppendLine(
                $"(({reg.TypeFullName})instance)[({idx.KeyTypeFullName})key] = ({idx.ValueTypeFullName})value!;");
            w.AppendLine("return true;");
        }
    }

    #endregion

    #region Constructors — only emitted when the type has public constructors

    private static void EmitTryCreateIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        if (reg.Constructors.Length == 0) return;

        w.AppendLine();
        using (w.Block("public override bool TryCreate(object?[] args, out object? instance)"))
        {
            using (w.Block("switch (args.Length)"))
            {
                foreach (var arityGroup in reg.Constructors.GroupBy(c => c.Parameters.Length).OrderBy(g => g.Key))
                {
                    var ctors = arityGroup.ToArray();
                    w.AppendLine($"case {arityGroup.Key}:");
                    w.Indent();

                    if (arityGroup.Key == 0)
                    {
                        w.AppendLine($"instance = new {reg.TypeFullName}(); return true;");
                    }
                    else
                    {
                        foreach (var ctor in ctors)
                        {
                            var condition = FormatTypeChecks(ctor.Parameters);
                            var castArgs = FormatCastArgs(ctor.Parameters);
                            w.AppendLine(
                                $"if ({condition}) {{ instance = new {reg.TypeFullName}({castArgs}); return true; }}");
                        }

                        w.AppendLine("instance = default; return false;");
                    }

                    w.Outdent();
                }

                w.AppendLine("default: instance = default; return false;");
            }
        }
    }

    #endregion

    #region Method invocation — only emitted when the type has matching methods

    private static void EmitTryInvokeIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        var methods = reg.Methods.Where(m => !m.IsStatic).ToArray();
        if (methods.Length == 0) return;

        w.AppendLine();
        EmitMethodDispatch(w,
            "public override bool TryInvoke(string name, object instance, object?[] args, out object? result)",
            reg.TypeFullName, methods, isStatic: false);
    }

    private static void EmitTryInvokeStaticIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        var methods = reg.Methods.Where(m => m.IsStatic).ToArray();
        if (methods.Length == 0) return;

        w.AppendLine();
        EmitMethodDispatch(w,
            "public override bool TryInvokeStatic(string name, object?[] args, out object? result)",
            reg.TypeFullName, methods, isStatic: true);
    }

    /// <summary>
    /// Emits method dispatch with nested switch: name → args.Length → type-checked overloads.
    /// Params methods are emitted after the args.Length switch as variable-arity fallbacks.
    /// </summary>
    private static void EmitMethodDispatch(
        SourceWriter w,
        string signature,
        string typeFullName,
        MethodModel[] methods,
        bool isStatic)
    {
        var target = isStatic ? typeFullName : "typed";

        using (w.Block(signature))
        {
            if (!isStatic)
                w.AppendLine($"var typed = ({typeFullName})instance;");

            using (w.Block("switch (name)"))
            {
                foreach (var nameGroup in methods.GroupBy(m => m.Name))
                {
                    var normalMethods = nameGroup.Where(m => !m.HasParams).ToArray();
                    var paramsMethods = nameGroup.Where(m => m.HasParams).ToArray();

                    w.AppendLine($"case \"{nameGroup.Key}\":");
                    w.Indent();

                    if (normalMethods.Length > 0)
                    {
                        using (w.Block("switch (args.Length)"))
                        {
                            foreach (var arityGroup in normalMethods.GroupBy(m => m.Parameters.Length))
                            {
                                var overloads = arityGroup.ToArray();
                                w.AppendLine($"case {arityGroup.Key}:");
                                w.Indent();
                                EmitOverloadDispatch(w, overloads, target);
                                w.AppendLine("break;");
                                w.Outdent();
                            }

                            w.AppendLine("default: break;");
                        }
                    }

                    foreach (var paramsMethod in paramsMethods)
                        EmitParamsDispatch(w, paramsMethod, target);

                    w.AppendLine("break;");
                    w.Outdent();
                }
            }

            w.AppendLine("result = default;");
            w.AppendLine("return false;");
        }
    }

    #endregion

    #region Params dispatch

    /// <summary>
    /// Emits dispatch for a params method. Handles two forms:
    /// 1. Normal form: caller passed the array directly (args.Length == paramCount, last arg is the array type)
    /// 2. Expanded form: caller passed individual elements (args.Length >= fixedCount), collected into an array at dispatch time
    /// </summary>
    private static void EmitParamsDispatch(SourceWriter w, MethodModel method, string target)
    {
        var paramsParam = method.Parameters[method.Parameters.Length - 1];
        var fixedCount = method.FixedParameterCount;

        // The params parameter type is an array (e.g., char[]). Extract the element type.
        var arrayType = paramsParam.TypeFullName;
        // "global::System.Char[]" → "global::System.Char"
        var elementType = arrayType.EndsWith("[]")
            ? arrayType.Substring(0, arrayType.Length - 2)
            : arrayType;

        // Normal form: caller passed the array directly
        {
            var normalCheck = FormatTypeChecks(method.Parameters);
            var normalArgs = FormatCastArgs(method.Parameters);
            var normalCall = $"{target}.{FormatMethodName(method)}({normalArgs})";
            var arityCheck = $"args.Length == {method.Parameters.Length}";

            if (method.ReturnsVoid)
                w.AppendLine($"if ({arityCheck} && {normalCheck}) {{ {normalCall}; result = null; return true; }}");
            else
                w.AppendLine($"if ({arityCheck} && {normalCheck}) {{ result = {normalCall}; return true; }}");
        }

        // Expanded form: collect individual elements into an array
        {
            var fixedChecks = new List<string>();
            fixedChecks.Add($"args.Length >= {fixedCount}");
            for (var i = 0; i < fixedCount; i++)
                fixedChecks.Add($"args[{i}] is {method.Parameters[i].TypeFullName}");

            var fixedCondition = string.Join(" && ", fixedChecks);

            using (w.Block($"if ({fixedCondition})"))
            {
                w.AppendLine($"var __paramsLen = args.Length - {fixedCount};");
                w.AppendLine($"var __paramsArr = new {elementType}[__paramsLen];");
                w.AppendLine("var __paramsOk = true;");
                using (w.Block("for (var __i = 0; __i < __paramsLen; __i++)"))
                {
                    using (w.Block($"if (args[__i + {fixedCount}] is {elementType} __elem)"))
                    {
                        w.AppendLine("__paramsArr[__i] = __elem;");
                    }
                    using (w.Block("else"))
                    {
                        w.AppendLine("__paramsOk = false; break;");
                    }
                }

                using (w.Block("if (__paramsOk)"))
                {
                    var callArgs = new List<string>();
                    for (var i = 0; i < fixedCount; i++)
                        callArgs.Add($"({method.Parameters[i].TypeFullName})args[{i}]!");
                    callArgs.Add("__paramsArr");

                    var call = $"{target}.{FormatMethodName(method)}({string.Join(", ", callArgs)})";
                    if (method.ReturnsVoid)
                        w.AppendLine($"{call}; result = null; return true;");
                    else
                        w.AppendLine($"result = {call}; return true;");
                }
            }
        }
    }

    #endregion

    #region Shared helpers

    private static void EmitOverloadDispatch(SourceWriter w, MethodModel[] methods, string target)
    {
        foreach (var method in methods)
        {
            var castArgs = FormatCastArgs(method.Parameters);
            var call = $"{target}.{FormatMethodName(method)}({castArgs})";

            if (method.Parameters.Length == 0)
            {
                if (method.ReturnsVoid)
                    w.AppendLine($"{call}; result = null; return true;");
                else
                    w.AppendLine($"result = {call}; return true;");
            }
            else
            {
                var condition = FormatTypeChecks(method.Parameters);
                if (method.ReturnsVoid)
                    w.AppendLine($"if ({condition}) {{ {call}; result = null; return true; }}");
                else
                    w.AppendLine($"if ({condition}) {{ result = {call}; return true; }}");
            }
        }
    }

    private static string FormatMethodName(MethodModel method)
    {
        if (!method.IsGenericInstantiation)
            return method.Name;
        return $"{method.Name}<{string.Join(", ", method.GenericTypeArgs)}>";
    }

    private static string FormatCastArgs(ImmutableArray<ParameterModel> parameters)
    {
        return string.Join(", ", parameters.Select((p, i) => $"({p.TypeFullName})args[{i}]!"));
    }

    private static string FormatTypeChecks(ImmutableArray<ParameterModel> parameters)
    {
        return string.Join(" && ", parameters.Select((p, i) => $"args[{i}] is {p.TypeFullName}"));
    }

    #endregion
}
