using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Alder.Generators.Model;

namespace Alder.Generators.Emitters;

/// <summary>
/// Emits AOT member-dispatch implementations for a registered CLR type.
/// The generated type roots keep closed generic shapes reachable in trimming and NativeAOT builds.
/// </summary>
internal static class TypeMetadataEmitter
{
    public static string Emit(TypeRegistrationModel reg)
    {
        var w = new SourceWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine("#nullable enable");
        w.AppendLine();

        using (w.Block($"file sealed class {reg.MetadataClassName} : global::Alder.Aot.TypedDispatch"))
        {
            w.AppendLine($"public override global::System.Type Type => typeof({reg.TypeFullName});");

            EmitTryGetIfNeeded(w, reg);
            EmitTrySetIfNeeded(w, reg);
            EmitTryGetStaticIfNeeded(w, reg);
            EmitTryGetIndexIfNeeded(w, reg);
            EmitTrySetIndexIfNeeded(w, reg);
            EmitTryCreateIfNeeded(w, reg);
            EmitTryInvokeIfNeeded(w, reg);
            EmitTryInvokeStaticIfNeeded(w, reg);
        }

        return w.ToString();
    }

    private static void EmitTryGetIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        var properties = reg.Properties.Where(p => p is { IsStatic: false, CanRead: true })
            .Select(p => (p.Name, $"value = typed.{p.Name}; return true;"));
        var fields = reg.Fields.Where(f => !f.IsStatic)
            .Select(f => (f.Name, $"value = typed.{f.Name}; return true;"));
        var cases = properties.Concat(fields).ToArray();

        if (cases.Length == 0) return;

        w.AppendLine();
        using (w.Block("public override bool TryGet(string name, object instance, out object? value)"))
        {
            w.AppendLine($"var typed = ({reg.TypeFullName})instance;");
            using (w.Block("switch (name)"))
            {
                foreach (var (name, body) in cases)
                    w.AppendLine($"case \"{name}\": {body}");
                w.AppendLine("default: value = default; return false;");
            }
        }
    }

    private static void EmitTrySetIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        // Unboxing a value type here would mutate a copy, so writable value types stay on the reflection path.
        if (reg.IsValueType) return;

        var properties = reg.Properties.Where(p => p is { IsStatic: false, CanWrite: true })
            .Select(p => (p.Name, $"typed.{p.Name} = ({p.TypeFullName})value!; return true;"));
        var fields = reg.Fields.Where(f => f is { IsStatic: false, IsReadOnly: false })
            .Select(f => (f.Name, $"typed.{f.Name} = ({f.TypeFullName})value!; return true;"));
        var cases = properties.Concat(fields).ToArray();

        if (cases.Length == 0) return;

        w.AppendLine();
        using (w.Block("public override bool TrySet(string name, object instance, object? value)"))
        {
            w.AppendLine($"var typed = ({reg.TypeFullName})instance;");
            using (w.Block("switch (name)"))
            {
                foreach (var (name, body) in cases)
                    w.AppendLine($"case \"{name}\": {body}");
                w.AppendLine("default: return false;");
            }
        }
    }

    private static void EmitTryGetStaticIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        var properties = reg.Properties.Where(p => p is { IsStatic: true, CanRead: true })
            .Select(p => (p.Name, $"value = {reg.TypeFullName}.{p.Name}; return true;"));
        var fields = reg.Fields.Where(f => f.IsStatic)
            .Select(f => (f.Name, $"value = {reg.TypeFullName}.{f.Name}; return true;"));
        var cases = properties.Concat(fields).ToArray();

        if (cases.Length == 0) return;

        w.AppendLine();
        using (w.Block("public override bool TryGetStatic(string name, out object? value)"))
        {
            using (w.Block("switch (name)"))
            {
                foreach (var (name, body) in cases)
                    w.AppendLine($"case \"{name}\": {body}");
                w.AppendLine("default: value = default; return false;");
            }
        }
    }

    private static void EmitTryGetIndexIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        var readable = reg.Indexers.Where(i => i.CanRead).ToArray();
        if (readable.Length == 0) return;

        w.AppendLine();
        using (w.Block("public override bool TryGetIndex(object instance, object key, out object? value)"))
        {
            foreach (var idx in readable)
            {
                w.AppendLine($"if (key is {idx.KeyTypeFullName}) {{ value = (({reg.TypeFullName})instance)[({idx.KeyTypeFullName})key]; return true; }}");
            }
            w.AppendLine("value = default; return false;");
        }
    }

    private static void EmitTrySetIndexIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        // Writable value-type indexers stay on the reflection path because unboxing would mutate a copy.
        if (reg.IsValueType) return;

        var writable = reg.Indexers.Where(i => i.CanWrite).ToArray();
        if (writable.Length == 0) return;

        w.AppendLine();
        using (w.Block("public override bool TrySetIndex(object instance, object key, object? value)"))
        {
            foreach (var idx in writable)
            {
                w.AppendLine($"if (key is {idx.KeyTypeFullName}) {{ (({reg.TypeFullName})instance)[({idx.KeyTypeFullName})key] = ({idx.ValueTypeFullName})value!; return true; }}");
            }
            w.AppendLine("return false;");
        }
    }

    private static void EmitTryCreateIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        if (reg.Constructors.Length == 0) return;

        w.AppendLine();
        using (w.Block("public override bool TryCreate(object?[] args, out object? instance)"))
        {
            using (w.Block("switch (args.Length)"))
            {
                foreach (var arityGroup in reg.Constructors.GroupBy(c => c.Parameters.Length).OrderBy(g => g.Key))
                {
                    var ctors = arityGroup.ToArray();
                    w.AppendLine($"case {arityGroup.Key}:");
                    w.Indent();

                    if (arityGroup.Key == 0)
                    {
                        w.AppendLine($"instance = new {reg.TypeFullName}(); return true;");
                    }
                    else
                    {
                        foreach (var ctor in ctors)
                        {
                            var condition = FormatTypeChecks(ctor.Parameters);
                            var castArgs = FormatCastArgs(ctor.Parameters);
                            w.AppendLine(
                                $"if ({condition}) {{ instance = new {reg.TypeFullName}({castArgs}); return true; }}");
                        }

                        w.AppendLine("instance = default; return false;");
                    }

                    w.Outdent();
                }

                w.AppendLine("default: instance = default; return false;");
            }
        }
    }

    private static void EmitTryInvokeIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        var methods = reg.Methods.Where(m => !m.IsStatic).ToArray();
        if (methods.Length == 0) return;

        w.AppendLine();
        EmitMethodDispatch(w,
            "public override bool TryInvoke(string name, object instance, object?[] args, out object? result)",
            reg.TypeFullName, methods, isStatic: false);
    }

    private static void EmitTryInvokeStaticIfNeeded(SourceWriter w, TypeRegistrationModel reg)
    {
        var methods = reg.Methods.Where(m => m.IsStatic).ToArray();
        if (methods.Length == 0) return;

        w.AppendLine();
        EmitMethodDispatch(w,
            "public override bool TryInvokeStatic(string name, object?[] args, out object? result)",
            reg.TypeFullName, methods, isStatic: true);
    }

    /// <summary>
    /// Emits method dispatch keyed first by member name and then by argument shape.
    /// Params methods are emitted as variable-arity fallbacks after the fixed-arity cases.
    /// </summary>
    private static void EmitMethodDispatch(
        SourceWriter w,
        string signature,
        string typeFullName,
        MethodModel[] methods,
        bool isStatic)
    {
        var target = isStatic ? typeFullName : "typed";

        using (w.Block(signature))
        {
            if (!isStatic)
                w.AppendLine($"var typed = ({typeFullName})instance;");

            using (w.Block("switch (name)"))
            {
                foreach (var nameGroup in methods.GroupBy(m => m.Name))
                {
                    var normalMethods = nameGroup.Where(m => !m.HasParams).ToArray();
                    var paramsMethods = nameGroup.Where(m => m.HasParams).ToArray();

                    w.AppendLine($"case \"{nameGroup.Key}\":");
                    w.Indent();

                    if (normalMethods.Length > 0)
                    {
                        using (w.Block("switch (args.Length)"))
                        {
                            foreach (var arityGroup in normalMethods.GroupBy(m => m.Parameters.Length))
                            {
                                var overloads = arityGroup.ToArray();
                                w.AppendLine($"case {arityGroup.Key}:");
                                w.Indent();
                                EmitOverloadDispatch(w, overloads, target);
                                w.AppendLine("break;");
                                w.Outdent();
                            }

                            w.AppendLine("default: break;");
                        }
                    }

                    foreach (var paramsMethod in paramsMethods)
                        EmitParamsDispatch(w, paramsMethod, target);

                    w.AppendLine("break;");
                    w.Outdent();
                }
            }

            w.AppendLine("result = default;");
            w.AppendLine("return false;");
        }
    }

    /// <summary>
    /// Emits dispatch for both params-call forms:
    /// direct array passing and expanded argument collection.
    /// </summary>
    private static void EmitParamsDispatch(SourceWriter w, MethodModel method, string target)
    {
        var paramsParam = method.Parameters[method.Parameters.Length - 1];
        var fixedCount = method.FixedParameterCount;

        var arrayType = paramsParam.TypeFullName;
        var elementType = arrayType.EndsWith("[]")
            ? arrayType.Substring(0, arrayType.Length - 2)
            : arrayType;

        // Direct array form.
        {
            var normalCheck = FormatTypeChecks(method.Parameters);
            var normalArgs = FormatCastArgs(method.Parameters);
            var normalCall = $"{target}.{FormatMethodName(method)}({normalArgs})";
            var arityCheck = $"args.Length == {method.Parameters.Length}";

            if (method.ReturnsVoid)
                w.AppendLine($"if ({arityCheck} && {normalCheck}) {{ {normalCall}; result = null; return true; }}");
            else
                w.AppendLine($"if ({arityCheck} && {normalCheck}) {{ result = {normalCall}; return true; }}");
        }

        // Expanded form.
        {
            var fixedChecks = new List<string>();
            fixedChecks.Add($"args.Length >= {fixedCount}");
            for (var i = 0; i < fixedCount; i++)
                fixedChecks.Add($"args[{i}] is {method.Parameters[i].TypeFullName}");

            var fixedCondition = string.Join(" && ", fixedChecks);

            using (w.Block($"if ({fixedCondition})"))
            {
                w.AppendLine($"var __paramsLen = args.Length - {fixedCount};");
                w.AppendLine($"var __paramsArr = new {elementType}[__paramsLen];");
                w.AppendLine("var __paramsOk = true;");
                using (w.Block("for (var __i = 0; __i < __paramsLen; __i++)"))
                {
                    using (w.Block($"if (args[__i + {fixedCount}] is {elementType} __elem)"))
                    {
                        w.AppendLine("__paramsArr[__i] = __elem;");
                    }
                    using (w.Block("else"))
                    {
                        w.AppendLine("__paramsOk = false; break;");
                    }
                }

                using (w.Block("if (__paramsOk)"))
                {
                    var callArgs = new List<string>();
                    for (var i = 0; i < fixedCount; i++)
                        callArgs.Add($"({method.Parameters[i].TypeFullName})args[{i}]!");
                    callArgs.Add("__paramsArr");

                    var call = $"{target}.{FormatMethodName(method)}({string.Join(", ", callArgs)})";
                    if (method.ReturnsVoid)
                        w.AppendLine($"{call}; result = null; return true;");
                    else
                        w.AppendLine($"result = {call}; return true;");
                }
            }
        }
    }

    private static void EmitOverloadDispatch(SourceWriter w, MethodModel[] methods, string target)
    {
        foreach (var method in methods)
        {
            if (method.Parameters.Length == 0)
            {
                EmitMethodCall(w, method, target);
                continue;
            }

            var condition = FormatTypeChecks(method.Parameters);
            using (w.Block($"if ({condition})"))
                EmitMethodCall(w, method, target);
        }
    }

    private static string FormatMethodName(MethodModel method)
    {
        return method.Name;
    }

    private static void EmitMethodCall(SourceWriter w, MethodModel method, string target)
    {
        var callArgs = new List<string>(method.Parameters.Length);

        for (var i = 0; i < method.Parameters.Length; i++)
        {
            var parameter = method.Parameters[i];
            if (parameter.IsOut)
            {
                w.AppendLine($"{parameter.DeclarationTypeFullName} __out{i} = default;");
                callArgs.Add($"out __out{i}");
                continue;
            }

            callArgs.Add($"({parameter.TypeFullName})args[{i}]!");
        }

        var call = $"{target}.{FormatMethodName(method)}({string.Join(", ", callArgs)})";
        if (method.ReturnsVoid)
            w.AppendLine($"{call};");
        else
            w.AppendLine($"result = {call};");

        for (var i = 0; i < method.Parameters.Length; i++)
        {
            if (method.Parameters[i].IsOut)
                w.AppendLine($"args[{i}] = __out{i};");
        }

        if (method.ReturnsVoid)
            w.AppendLine("result = null;");

        w.AppendLine("return true;");
    }

    private static string FormatCastArgs(ImmutableArray<ParameterModel> parameters)
    {
        return string.Join(", ", parameters.Select((p, i) => p.IsOut ? $"out __out{i}" : $"({p.TypeFullName})args[{i}]!"));
    }

    private static string FormatTypeChecks(ImmutableArray<ParameterModel> parameters)
    {
        var checks = parameters
            .Select((p, i) => p.IsOut ? null : $"args[{i}] is {p.TypeFullName}")
            .Where(static check => check != null)
            .ToArray();

        return checks.Length == 0 ? "true" : string.Join(" && ", checks);
    }
}
